package analyzer

import (
	"github.com/miyamo2/braider/internal/registry"
	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"golang.org/x/tools/go/analysis/checker"
)

// Aggregator holds shared state between the dependency and app analysis phases.
// AfterDependencyPhase aggregates per-package DependencyResults into shared registries.
type Aggregator struct {
	annotation.Injectable[inject.Default]
	ProviderRegistry  *registry.ProviderRegistry
	InjectorRegistry  *registry.InjectorRegistry
	VariableRegistry  *registry.VariableRegistry
	DuplicateRegistry *registry.DuplicateRegistry
}

// NewAggregator is a constructor for Aggregator.
//
// Generated by braider. DO NOT EDIT.
func NewAggregator(providerRegistry *registry.ProviderRegistry, injectorRegistry *registry.InjectorRegistry, variableRegistry *registry.VariableRegistry, duplicateRegistry *registry.DuplicateRegistry) *Aggregator {
	return &Aggregator{
		ProviderRegistry:  providerRegistry,
		InjectorRegistry:  injectorRegistry,
		VariableRegistry:  variableRegistry,
		DuplicateRegistry: duplicateRegistry,
	}
}

// AfterDependencyPhase is the phasedchecker AfterPhase callback for the dependency phase.
// It iterates all actions in the graph, extracts DependencyResults, and registers
// collected providers, injectors, and variables into the shared registries.
// Duplicate (TypeName, Name) registration errors are collected into DuplicateRegistry
// for reporting by AppAnalyzeRunner in the subsequent phase.
func (a *Aggregator) AfterDependencyPhase(graph *checker.Graph) error {
	for act := range graph.All() {
		if act.Result == nil {
			continue
		}
		result, ok := act.Result.(*DependencyResult)
		if !ok || result == nil {
			continue
		}
		for _, p := range result.Providers {
			if err := a.ProviderRegistry.Register(p); err != nil {
				existingLocation := p.PackagePath
				if existing, ok := a.ProviderRegistry.GetByName(p.TypeName, p.Name); ok {
					existingLocation = existing.PackagePath
				}
				a.DuplicateRegistry.Add(registry.DuplicateRegistration{
					TypeName: p.TypeName, Name: p.Name, Location1: existingLocation, Location2: p.PackagePath,
				})
			}
		}
		for _, i := range result.Injectors {
			if err := a.InjectorRegistry.Register(i); err != nil {
				existingLocation := i.PackagePath
				if existing, ok := a.InjectorRegistry.GetByName(i.TypeName, i.Name); ok {
					existingLocation = existing.PackagePath
				}
				a.DuplicateRegistry.Add(registry.DuplicateRegistration{
					TypeName: i.TypeName, Name: i.Name, Location1: existingLocation, Location2: i.PackagePath,
				})
			}
		}
		for _, v := range result.Variables {
			if err := a.VariableRegistry.Register(v); err != nil {
				existingLocation := v.PackagePath
				if existing, ok := a.VariableRegistry.GetByName(v.TypeName, v.Name); ok {
					existingLocation = existing.PackagePath
				}
				a.DuplicateRegistry.Add(registry.DuplicateRegistration{
					TypeName: v.TypeName, Name: v.Name, Location1: existingLocation, Location2: v.PackagePath,
				})
			}
		}
	}
	return nil
}
