package analyzer

import (
	"github.com/miyamo2/braider/internal/registry"
	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"golang.org/x/tools/go/analysis/checker"
)

// Aggregator holds shared state between the dependency and app analysis phases.
// AfterDependencyPhase aggregates per-package DependencyResults into shared registries.
type Aggregator struct {
	annotation.Injectable[inject.Default]
	ProviderRegistry *registry.ProviderRegistry
	InjectorRegistry *registry.InjectorRegistry
	VariableRegistry *registry.VariableRegistry
}

// NewAggregator is a constructor for Aggregator.
//
// Generated by braider. DO NOT EDIT.
func NewAggregator(providerRegistry *registry.ProviderRegistry, injectorRegistry *registry.InjectorRegistry, variableRegistry *registry.VariableRegistry) *Aggregator {
	return &Aggregator{
		ProviderRegistry: providerRegistry,
		InjectorRegistry: injectorRegistry,
		VariableRegistry: variableRegistry,
	}
}

// AfterDependencyPhase is the phasedchecker AfterPhase callback for the dependency phase.
// It iterates all actions in the graph, extracts DependencyResults, and registers
// collected providers, injectors, and variables into the shared registries.
func (a *Aggregator) AfterDependencyPhase(graph *checker.Graph) error {
	for act := range graph.All() {
		if act.Result == nil {
			continue
		}
		result, ok := act.Result.(*DependencyResult)
		if !ok || result == nil {
			continue
		}
		for _, p := range result.Providers {
			a.ProviderRegistry.Register(p)
		}
		for _, i := range result.Injectors {
			a.InjectorRegistry.Register(i)
		}
		for _, v := range result.Variables {
			a.VariableRegistry.Register(v)
		}
	}
	return nil
}
