package analyzer

import (
	"context"
	"errors"
	"fmt"
	"go/ast"
	"strings"

	"github.com/miyamo2/braider/internal/detect"
	"github.com/miyamo2/braider/internal/generate"
	"github.com/miyamo2/braider/internal/graph"
	"github.com/miyamo2/braider/internal/loader"
	"github.com/miyamo2/braider/internal/registry"
	"github.com/miyamo2/braider/internal/report"
	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"github.com/miyamo2/braider/pkg/annotation/provide"
	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
)

var _ = annotation.Provide[provide.Default](NewAppAnalyzer)

type AppAnalyzer analysis.Analyzer

// NewAppAnalyzer detects annotation.App(main) and generates bootstrap code.
func NewAppAnalyzer(
	runner *AppAnalyzeRunner,
) *AppAnalyzer {
	return (*AppAnalyzer)(
		&analysis.Analyzer{
			Name:     "braider_app",
			Doc:      "detects App annotation and generates IIFE bootstrap code",
			Run:      runner.Run,
			Requires: []*analysis.Analyzer{inspect.Analyzer},
		},
	)
}

type AppAnalyzeRunner struct {
	annotation.Injectable[inject.Default]
	appDetector        detect.AppDetector
	injectRegistry     *registry.InjectorRegistry
	provideRegistry    *registry.ProviderRegistry
	packageLoader      loader.PackageLoader
	packageTracker     *registry.PackageTracker
	bootstrapCtx       context.Context
	graphBuilder       *graph.DependencyGraphBuilder
	sorter             *graph.TopologicalSorter
	bootstrapGen       generate.BootstrapGenerator
	fixBuilder         report.SuggestedFixBuilder
	diagnosticEmitter  report.DiagnosticEmitter
	variableRegistry   *registry.VariableRegistry
	appOptionExtractor detect.AppOptionExtractor
	containerValidator graph.ContainerValidator
	containerResolver  graph.ContainerResolver
}

// NewAppAnalyzeRunner is a constructor for AppAnalyzeRunner.
//
// Generated by braider. DO NOT EDIT.
func NewAppAnalyzeRunner(
	appDetector detect.AppDetector, injectRegistry *registry.InjectorRegistry,
	provideRegistry *registry.ProviderRegistry, packageLoader loader.PackageLoader,
	packageTracker *registry.PackageTracker, bootstrapCtx context.Context, graphBuilder *graph.DependencyGraphBuilder,
	sorter *graph.TopologicalSorter, bootstrapGen generate.BootstrapGenerator, fixBuilder report.SuggestedFixBuilder,
	diagnosticEmitter report.DiagnosticEmitter, variableRegistry *registry.VariableRegistry,
	appOptionExtractor detect.AppOptionExtractor, containerValidator graph.ContainerValidator,
	containerResolver graph.ContainerResolver,
) *AppAnalyzeRunner {
	return &AppAnalyzeRunner{
		appDetector:        appDetector,
		injectRegistry:     injectRegistry,
		provideRegistry:    provideRegistry,
		packageLoader:      packageLoader,
		packageTracker:     packageTracker,
		bootstrapCtx:       bootstrapCtx,
		graphBuilder:       graphBuilder,
		sorter:             sorter,
		bootstrapGen:       bootstrapGen,
		fixBuilder:         fixBuilder,
		diagnosticEmitter:  diagnosticEmitter,
		variableRegistry:   variableRegistry,
		appOptionExtractor: appOptionExtractor,
		containerValidator: containerValidator,
		containerResolver:  containerResolver,
	}
}

func (r *AppAnalyzeRunner) Run(pass *analysis.Pass) (interface{}, error) {
	return r.run(r.bootstrapCtx, pass)
}

func (r *AppAnalyzeRunner) run(ctx context.Context, pass *analysis.Pass) (interface{}, error) {
	// Early context cancellation check
	if err := ctx.Err(); err != nil {
		return nil, nil
	}

	reporter := &passReporter{pass: pass}
	// Phase 1: Detect App annotations
	apps := r.appDetector.DetectAppAnnotations(pass)

	// Skip if no App annotation present
	if len(apps) == 0 {
		return nil, nil
	}

	// Phase 1.5: Deduplicate by file (same file → first only)
	allApps := apps
	apps = r.appDetector.DeduplicateAppsByFile(apps)

	// Report warnings for duplicates (apps that were removed)
	// Use map for O(n) lookup instead of O(n²) with slices.Contains
	dedupedSet := make(map[*detect.AppAnnotation]bool)
	for _, app := range apps {
		dedupedSet[app] = true
	}

	for _, app := range allApps {
		if !dedupedSet[app] {
			r.diagnosticEmitter.EmitDuplicateAppWarning(reporter, app.Pos)
		}
	}

	// Phase 2: Validate App annotations
	if err := r.appDetector.ValidateAppAnnotations(pass, apps); err != nil {
		// Report validation error
		if appErr, ok := err.(*detect.AppValidationError); ok {
			switch appErr.Type {
			case detect.NonMainReference:
				r.diagnosticEmitter.EmitNonMainAppError(reporter, appErr.Positions[0], appErr.FuncName)
			}
			// Skip bootstrap generation after validation error
			return nil, nil
		}
		// Unknown error type, skip bootstrap
		return nil, nil
	}

	// Phase 2: Wait for all packages to be scanned
	// Defensive programming: ensure pass.Files is not empty
	if len(pass.Files) == 0 {
		// This should not happen in normal analyzer execution, but handle it defensively
		return nil, fmt.Errorf("no files in pass")
	}

	allPkgPaths, err := r.packageLoader.LoadModulePackageNames(pass.Fset.File(pass.Files[0].Pos()).Name())
	if err != nil {
		// Emit warning diagnostic (non-critical)
		// The registry may be incomplete, but we proceed with what we have
		r.diagnosticEmitter.EmitPackageLoadWarning(reporter, apps[0].Pos, err.Error())
	}

	// Wait for all packages with timeout
	if len(allPkgPaths) > 0 {
		if err := r.packageTracker.WaitForAllPackagesWithContext(ctx, allPkgPaths); err != nil {
			if errors.Is(err, context.Canceled) {
				return nil, nil
			}
			// Emit timeout warning diagnostic but continue
			// The registry may be incomplete, but we proceed with what we have
			r.diagnosticEmitter.EmitPackageWaitWarning(reporter, apps[0].Pos, err.Error())
		}
	}

	// Phase 3: Retrieve all providers, injectors, and variables from global registries
	providers := r.provideRegistry.GetAll()
	injectors := r.injectRegistry.GetAll()
	var variables []*registry.VariableInfo
	if r.variableRegistry != nil {
		variables = r.variableRegistry.GetAll()
	}

	// Phase 4: Build dependency graph
	depGraph, err := r.graphBuilder.BuildGraph(pass, providers, injectors, variables)
	if err != nil {
		// Check for unresolvable type with name mismatch hint (Req 6.5)
		errMsg := err.Error()
		if unresolvedErr, ok := err.(*graph.UnresolvableTypeError); ok && r.variableRegistry != nil {
			hint := r.buildNameMismatchHint(unresolvedErr.TypeName)
			if hint != "" {
				errMsg = errMsg + "; " + hint
			}
		}
		r.diagnosticEmitter.EmitGraphBuildError(reporter, apps[0].Pos, errMsg)
		return nil, nil
	}

	// Execute topological sort
	sortedTypes, err := r.sorter.Sort(depGraph)
	if err != nil {
		if cycleErr, ok := err.(*graph.CycleError); ok {
			r.diagnosticEmitter.EmitCircularDependency(reporter, apps[0].Pos, cycleErr.Cycle)
			return nil, nil
		}
		// Unknown topological sort error - report for debugging
		r.diagnosticEmitter.EmitGraphBuildError(reporter, apps[0].Pos, err.Error())
		return nil, nil
	}

	// Phase 5: Extract app option to determine mode (default vs container)
	optionMeta, optionErr := r.appOptionExtractor.ExtractAppOption(pass, apps[0])

	// Handle container-related option extraction errors (e.g. non-struct type parameter)
	if optionErr != nil && !optionMeta.IsDefault {
		r.diagnosticEmitter.EmitGraphBuildError(reporter, apps[0].Pos, optionErr.Error())
		return nil, nil
	}

	// Find main function (needed for both modes)
	mainFunc := findMainFunction(pass)
	if mainFunc == nil {
		return nil, nil
	}

	existingBootstrap := r.bootstrapGen.DetectExistingBootstrap(pass)

	if optionErr == nil && optionMeta.ContainerDef != nil {
		// Container mode
		containerDef := optionMeta.ContainerDef

		// 1. Validate container fields
		validationErrors := r.containerValidator.Validate(containerDef, depGraph)
		if len(validationErrors) > 0 {
			for _, verr := range validationErrors {
				if verr.FieldName != "" {
					r.diagnosticEmitter.EmitContainerFieldError(reporter, verr.Pos, verr.FieldName, "", verr.Message)
				} else {
					r.diagnosticEmitter.EmitContainerTypeError(reporter, verr.Pos, verr.Message)
				}
			}
			return nil, nil
		}

		// 2. Resolve container fields
		resolvedFields, resolveErr := r.containerResolver.ResolveFields(containerDef, depGraph)
		if resolveErr != nil {
			r.diagnosticEmitter.EmitGraphBuildError(reporter, apps[0].Pos, resolveErr.Error())
			return nil, nil
		}

		// 3. Check idempotency
		if existingBootstrap != nil {
			if r.bootstrapGen.CheckContainerBootstrapCurrent(pass, existingBootstrap, depGraph, containerDef) {
				return nil, nil
			}
		}

		// 4. Generate container bootstrap
		bootstrap, genErr := r.bootstrapGen.GenerateContainerBootstrap(pass, depGraph, sortedTypes, containerDef, resolvedFields)
		if genErr != nil {
			r.diagnosticEmitter.EmitGenerationError(reporter, apps[0].Pos, "container bootstrap", genErr.Error())
			return nil, nil
		}

		// 5. Build and emit fix
		var fix analysis.SuggestedFix
		if existingBootstrap != nil {
			fix = r.fixBuilder.BuildBootstrapReplacementFix(pass, existingBootstrap, bootstrap, mainFunc)
			r.diagnosticEmitter.EmitBootstrapUpdateFix(reporter, apps[0].Pos, fix)
		} else {
			fix = r.fixBuilder.BuildBootstrapFix(pass, apps[0], bootstrap, mainFunc)
			r.diagnosticEmitter.EmitBootstrapFix(reporter, apps[0].Pos, fix)
		}
	} else {
		// Default mode (existing behavior)
		if existingBootstrap != nil {
			if r.bootstrapGen.CheckBootstrapCurrent(pass, existingBootstrap, depGraph) {
				return nil, nil
			}
		}

		bootstrap, genErr := r.bootstrapGen.GenerateBootstrap(pass, depGraph, sortedTypes)
		if genErr != nil {
			r.diagnosticEmitter.EmitGenerationError(reporter, apps[0].Pos, "bootstrap", genErr.Error())
			return nil, nil
		}

		var fix analysis.SuggestedFix
		if existingBootstrap != nil {
			fix = r.fixBuilder.BuildBootstrapReplacementFix(pass, existingBootstrap, bootstrap, mainFunc)
			r.diagnosticEmitter.EmitBootstrapUpdateFix(reporter, apps[0].Pos, fix)
		} else {
			fix = r.fixBuilder.BuildBootstrapFix(pass, apps[0], bootstrap, mainFunc)
			r.diagnosticEmitter.EmitBootstrapFix(reporter, apps[0].Pos, fix)
		}
	}

	return nil, nil
}

// buildNameMismatchHint checks if an unresolvable dependency type matches a Variable
// registration with a different name, and returns a hint message if so.
func (r *AppAnalyzeRunner) buildNameMismatchHint(typeName string) string {
	// Strip pointer prefix for lookup
	normalizedName := typeName
	if strings.HasPrefix(typeName, "*") {
		normalizedName = typeName[1:]
	}

	availableNames := r.variableRegistry.GetNamesByType(normalizedName)
	if len(availableNames) == 0 {
		return ""
	}

	// Build hint with available named variants
	var hints []string
	for _, name := range availableNames {
		hints = append(hints, normalizedName+"#"+name)
	}
	return fmt.Sprintf("did you mean %s?", strings.Join(hints, " or "))
}

// findMainFunction finds the main function declaration in the package.
func findMainFunction(pass *analysis.Pass) *ast.FuncDecl {
	for _, file := range pass.Files {
		for _, decl := range file.Decls {
			if fn, ok := decl.(*ast.FuncDecl); ok {
				if fn.Name.Name == "main" {
					return fn
				}
			}
		}
	}
	return nil
}
