package analyzer

import (
	"fmt"
	"strings"

	"github.com/miyamo2/braider/internal/detect"
	"github.com/miyamo2/braider/internal/generate"
	"github.com/miyamo2/braider/internal/graph"
	"github.com/miyamo2/braider/internal/registry"
	"github.com/miyamo2/braider/internal/report"
	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"github.com/miyamo2/braider/pkg/annotation/provide"
	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
)

var _ = annotation.Provide[provide.Named[AppAnalyzerNamer]](NewAppAnalyzer)

type AppAnalyzerNamer struct{}

func (n AppAnalyzerNamer) Name() string {
	return "appAnalyzer"
}

// NewAppAnalyzer detects annotation.App(main) and generates bootstrap code.
func NewAppAnalyzer(
	runner *AppAnalyzeRunner,
) *analysis.Analyzer {
	return &analysis.Analyzer{
		Name:     "braider_app",
		Doc:      "detects App annotation and generates IIFE bootstrap code",
		Run:      runner.Run,
		Requires: []*analysis.Analyzer{inspect.Analyzer},
	}
}

type AppAnalyzeRunner struct {
	annotation.Injectable[inject.Default]
	appDetector        detect.AppDetector
	injectRegistry     *registry.InjectorRegistry
	provideRegistry    *registry.ProviderRegistry
	graphBuilder       *graph.DependencyGraphBuilder
	sorter             *graph.TopologicalSorter
	bootstrapGen       generate.BootstrapGenerator
	fixBuilder         report.SuggestedFixBuilder
	diagnosticEmitter  report.DiagnosticEmitter
	variableRegistry   *registry.VariableRegistry
	appOptionExtractor detect.AppOptionExtractor
	containerValidator graph.ContainerValidator
	containerResolver  graph.ContainerResolver
	duplicateRegistry  *registry.DuplicateRegistry
	entryPointRegistry *registry.EntryPointRegistry
}

// NewAppAnalyzeRunner is a constructor for AppAnalyzeRunner.
//
// Generated by braider. DO NOT EDIT.
func NewAppAnalyzeRunner(
	appDetector detect.AppDetector, injectRegistry *registry.InjectorRegistry,
	provideRegistry *registry.ProviderRegistry,
	graphBuilder *graph.DependencyGraphBuilder,
	sorter *graph.TopologicalSorter, bootstrapGen generate.BootstrapGenerator, fixBuilder report.SuggestedFixBuilder,
	diagnosticEmitter report.DiagnosticEmitter, variableRegistry *registry.VariableRegistry,
	appOptionExtractor detect.AppOptionExtractor, containerValidator graph.ContainerValidator,
	containerResolver graph.ContainerResolver, duplicateRegistry *registry.DuplicateRegistry,
	entryPointRegistry *registry.EntryPointRegistry,
) *AppAnalyzeRunner {
	return &AppAnalyzeRunner{
		appDetector:        appDetector,
		injectRegistry:     injectRegistry,
		provideRegistry:    provideRegistry,
		graphBuilder:       graphBuilder,
		sorter:             sorter,
		bootstrapGen:       bootstrapGen,
		fixBuilder:         fixBuilder,
		diagnosticEmitter:  diagnosticEmitter,
		variableRegistry:   variableRegistry,
		appOptionExtractor: appOptionExtractor,
		containerValidator: containerValidator,
		containerResolver:  containerResolver,
		duplicateRegistry:  duplicateRegistry,
		entryPointRegistry: entryPointRegistry,
	}
}

func (r *AppAnalyzeRunner) Run(pass *analysis.Pass) (interface{}, error) {
	reporter := &passReporter{pass: pass}
	// Detect App annotations
	apps := r.appDetector.DetectAppAnnotations(pass)

	// No explicit App annotation in this package: consider inference.
	//
	// Inference rule (Requirement 1.x / 3.x):
	//   - If any explicit App annotation exists anywhere in scope, do nothing
	//     here (explicit always wins; the package owning it will generate).
	//   - Otherwise, if this package is a main package AND exactly one main
	//     package exists in scope, synthesize an inferred AppAnnotation and
	//     route it through the existing default-mode bootstrap pipeline.
	//   - If this package is a main package AND multiple main packages exist
	//     in scope, emit the ambiguity diagnostic at this package's main and
	//     skip generation.
	//   - Otherwise (not a main package, or no main func), do nothing.
	if len(apps) == 0 {
		if r.entryPointRegistry == nil {
			return nil, nil
		}
		if r.entryPointRegistry.HasExplicitApp() {
			return nil, nil
		}
		mainFunc := findMainFunction(pass)
		if mainFunc == nil {
			return nil, nil
		}
		mainPaths := r.entryPointRegistry.MainPackagePaths()
		switch {
		case len(mainPaths) > 1:
			r.diagnosticEmitter.EmitAmbiguousEntryPoint(reporter, mainFunc.Pos(), mainPaths)
			return nil, nil
		case len(mainPaths) == 1:
			apps = []*detect.AppAnnotation{{
				File:     findFileForFunc(pass, mainFunc),
				Pos:      mainFunc.Pos(),
				Inferred: true,
			}}
		default:
			// No main packages registered (defensive — should not happen when
			// mainFunc != nil because the dependency phase would have registered
			// this package).
			return nil, nil
		}
	}

	// Deduplicate by file (same file → first only). Inferred entries are a
	// single synthetic value; dedup is a no-op for them but harmless.
	allApps := apps
	apps = r.appDetector.DeduplicateAppsByFile(apps)

	// Report warnings for duplicates (apps that were removed).
	// Skip duplicate-warning emission entirely for inferred values: dedup is a
	// no-op when the only entry is synthetic.
	if !apps[0].Inferred {
		dedupedSet := make(map[*detect.AppAnnotation]bool)
		for _, app := range apps {
			dedupedSet[app] = true
		}
		for _, app := range allApps {
			if !dedupedSet[app] {
				r.diagnosticEmitter.EmitDuplicateAppWarning(reporter, app.Pos)
			}
		}
	}

	// Validate App annotations (skipped for inferred entries — there is no
	// CallExpr / MainFunc ident to validate; synthesis already guarantees the
	// main function exists).
	if !apps[0].Inferred {
		if err := r.appDetector.ValidateAppAnnotations(pass, apps); err != nil {
			// Report validation error
			if appErr, ok := err.(*detect.AppValidationError); ok {
				switch appErr.Type {
				case detect.NonMainReference:
					r.diagnosticEmitter.EmitNonMainAppError(reporter, appErr.Positions[0], appErr.FuncName)
				}
				// Skip bootstrap generation after validation error
				return nil, nil
			}
			// Unknown error type, skip bootstrap
			return nil, nil
		}
	}

	// Report duplicate registration errors collected during dependency phase
	if r.duplicateRegistry != nil {
		duplicates := r.duplicateRegistry.GetAll()
		for _, dup := range duplicates {
			r.diagnosticEmitter.EmitDuplicateNamedDependencyWarning(
				reporter, apps[0].Pos, dup.TypeName, dup.Name, dup.Location1, dup.Location2,
			)
		}
		if len(duplicates) > 0 {
			return nil, nil
		}
	}

	// Retrieve all providers, injectors, and variables from shared registries
	providers := r.provideRegistry.GetAll()
	injectors := r.injectRegistry.GetAll()
	var variables []*registry.VariableInfo
	if r.variableRegistry != nil {
		variables = r.variableRegistry.GetAll()
	}

	// Build dependency graph
	depGraph, err := r.graphBuilder.BuildGraph(pass, providers, injectors, variables)
	if err != nil {
		// Check for unresolvable type with name mismatch hint
		errMsg := err.Error()
		if unresolvedErr, ok := err.(*graph.UnresolvableTypeError); ok && r.variableRegistry != nil {
			hint := r.buildNameMismatchHint(unresolvedErr.TypeName)
			if hint != "" {
				errMsg = errMsg + "; " + hint
			}
		}
		r.diagnosticEmitter.EmitGraphBuildError(reporter, apps[0].Pos, errMsg)
		return nil, nil
	}

	// Execute topological sort
	sortedTypes, err := r.sorter.Sort(depGraph)
	if err != nil {
		if cycleErr, ok := err.(*graph.CycleError); ok {
			r.diagnosticEmitter.EmitCircularDependency(reporter, apps[0].Pos, cycleErr.Cycle)
			return nil, nil
		}
		// Unknown topological sort error - report for debugging
		r.diagnosticEmitter.EmitGraphBuildError(reporter, apps[0].Pos, err.Error())
		return nil, nil
	}

	// Extract app option to determine mode (default vs container).
	// Inferred entries always run in default mode: there is no source CallExpr
	// to extract type-parameter information from, and Container[T] cannot be
	// inferred (no user-supplied container type).
	var optionMeta detect.AppOptionMetadata
	if !apps[0].Inferred {
		var optionErr error
		optionMeta, optionErr = r.appOptionExtractor.ExtractAppOption(pass, apps[0])
		// Handle option extraction errors (e.g. non-struct type parameter)
		if optionErr != nil {
			r.diagnosticEmitter.EmitGraphBuildError(reporter, apps[0].Pos, optionErr.Error())
			return nil, nil
		}
	}

	// Find main function (needed for both modes)
	mainFunc := findMainFunction(pass)
	if mainFunc == nil {
		return nil, nil
	}

	existingBootstrap := r.bootstrapGen.DetectExistingBootstrap(pass)

	if optionMeta.ContainerDef != nil {
		// Container mode
		containerDef := optionMeta.ContainerDef

		// Validate container fields
		validationErrors := r.containerValidator.Validate(containerDef, depGraph)
		if len(validationErrors) > 0 {
			for _, verr := range validationErrors {
				if verr.FieldName != "" {
					r.diagnosticEmitter.EmitContainerFieldError(reporter, verr.Pos, verr.FieldName, "", verr.Message)
				} else {
					r.diagnosticEmitter.EmitContainerTypeError(reporter, verr.Pos, verr.Message)
				}
			}
			return nil, nil
		}

		// Resolve container fields
		resolvedFields, resolveErr := r.containerResolver.ResolveFields(containerDef, depGraph)
		if resolveErr != nil {
			r.diagnosticEmitter.EmitGraphBuildError(reporter, apps[0].Pos, resolveErr.Error())
			return nil, nil
		}

		// Check idempotency
		if existingBootstrap != nil {
			if r.bootstrapGen.CheckContainerBootstrapCurrent(pass, existingBootstrap, depGraph, containerDef) {
				return nil, nil
			}
		}

		// Generate container bootstrap
		bootstrap, genErr := r.bootstrapGen.GenerateContainerBootstrap(
			pass,
			depGraph,
			sortedTypes,
			containerDef,
			resolvedFields,
		)
		if genErr != nil {
			r.diagnosticEmitter.EmitGenerationError(reporter, apps[0].Pos, "container bootstrap", genErr.Error())
			return nil, nil
		}

		// Build and emit fix
		var fix analysis.SuggestedFix
		var fixErr error
		if existingBootstrap != nil {
			fix, fixErr = r.fixBuilder.BuildBootstrapReplacementFix(pass, existingBootstrap, bootstrap, mainFunc)
			if fixErr != nil {
				r.diagnosticEmitter.EmitGenerationError(reporter, apps[0].Pos, "bootstrap fix", fixErr.Error())
				return nil, nil
			}
			r.diagnosticEmitter.EmitBootstrapUpdateFix(reporter, apps[0].Pos, fix)
		} else {
			fix, fixErr = r.fixBuilder.BuildBootstrapFix(pass, apps[0], bootstrap, mainFunc)
			if fixErr != nil {
				r.diagnosticEmitter.EmitGenerationError(reporter, apps[0].Pos, "bootstrap fix", fixErr.Error())
				return nil, nil
			}
			r.diagnosticEmitter.EmitBootstrapFix(reporter, apps[0].Pos, fix)
		}
	} else {
		// Default mode (existing behavior, also used for inferred entries).
		if existingBootstrap != nil {
			if r.bootstrapGen.CheckBootstrapCurrent(pass, existingBootstrap, depGraph) {
				return nil, nil
			}
		}

		bootstrap, genErr := r.bootstrapGen.GenerateBootstrap(pass, depGraph, sortedTypes)
		if genErr != nil {
			r.diagnosticEmitter.EmitGenerationError(reporter, apps[0].Pos, "bootstrap", genErr.Error())
			return nil, nil
		}

		var fix analysis.SuggestedFix
		var fixErr error
		if existingBootstrap != nil {
			fix, fixErr = r.fixBuilder.BuildBootstrapReplacementFix(pass, existingBootstrap, bootstrap, mainFunc)
			if fixErr != nil {
				r.diagnosticEmitter.EmitGenerationError(reporter, apps[0].Pos, "bootstrap fix", fixErr.Error())
				return nil, nil
			}
			if apps[0].Inferred {
				r.diagnosticEmitter.EmitInferredBootstrapUpdateFix(reporter, apps[0].Pos, fix)
			} else {
				r.diagnosticEmitter.EmitBootstrapUpdateFix(reporter, apps[0].Pos, fix)
			}
		} else {
			fix, fixErr = r.fixBuilder.BuildBootstrapFix(pass, apps[0], bootstrap, mainFunc)
			if fixErr != nil {
				r.diagnosticEmitter.EmitGenerationError(reporter, apps[0].Pos, "bootstrap fix", fixErr.Error())
				return nil, nil
			}
			if apps[0].Inferred {
				r.diagnosticEmitter.EmitInferredBootstrapFix(reporter, apps[0].Pos, fix)
			} else {
				r.diagnosticEmitter.EmitBootstrapFix(reporter, apps[0].Pos, fix)
			}
		}
	}

	return nil, nil
}

// buildNameMismatchHint checks if an unresolvable dependency type matches a Variable
// registration with a different name, and returns a hint message if so.
func (r *AppAnalyzeRunner) buildNameMismatchHint(typeName string) string {
	// Strip pointer prefix for lookup
	normalizedName := typeName
	if strings.HasPrefix(typeName, "*") {
		normalizedName = typeName[1:]
	}

	availableNames := r.variableRegistry.GetNamesByType(normalizedName)
	if len(availableNames) == 0 {
		return ""
	}

	// Build hint with available named variants
	var hints []string
	for _, name := range availableNames {
		hints = append(hints, normalizedName+"#"+name)
	}
	return fmt.Sprintf("did you mean %s?", strings.Join(hints, " or "))
}

