coverage:
  if: true
  acceptable: 70%
  exclude:
    - 'github.com/miyamo2/braider/cmd/**/*'
    - 'github.com/miyamo2/braider/pkg/**/*'
codeToTestRatio:
  code:
    - '**/*.go'
    - '!cmd/*.go'
    - '!pkg/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  if: true
comment:
  if: is_pull_request
body:
  if: is_pull_request
summary:
  if: true
diff:
  datastores:
    - github://miyamo2/octocov-central/.
report:
  if: is_default_branch
  datastores:
    - github://miyamo2/octocov-central/.
push:
  if: is_default_branch
  datastores:
    - github://miyamo2/octocov-central/.
  message: "Update coverage badges"