coverage:
  if: true
  acceptable: 70%
  exclude:
    - 'github.com/miyamo2/braider/cmd/**/*'
    - 'github.com/miyamo2/braider/pkg/**/*'
    - 'github.com/miyamo2/braider/internal/x/**/*'
  paths:
    - 'coverage.out'
  badge:
    path: .assets/test_cov.svg
codeToTestRatio:
  code:
    - '**/*.go'
    - '!cmd/**/*.go'
    - '!pkg/*.go'
    - '!internal/x/**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
  badge:
    path: .assets/ratio.svg
testExecutionTime:
  if: true
  badge:
    path: .assets/time.svg
comment:
  if: is_pull_request
body:
  if: is_pull_request
summary:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
    - github://miyamo2/octocov-central/.
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
    - github://miyamo2/octocov-central/.
push:
  if: is_default_branch
  datastores:
    - github://${GITHUB_REPOSITORY}
    - github://miyamo2/octocov-central/.
  message: "Update coverage badges"