package detect

import (
	"fmt"
	"go/token"
	"go/types"
	"reflect"
	"strings"

	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"golang.org/x/tools/go/analysis"
)

const (
	internalAnnotationPath = "github.com/miyamo2/braider/internal/annotation"
	appOptionsPath         = "github.com/miyamo2/braider/pkg/annotation/app"
)

// AppOptionExtractor extracts App option metadata from type arguments.
type AppOptionExtractor interface {
	// ExtractAppOption extracts the App option from the detected annotation.
	// Returns AppOptionMetadata with either IsDefault=true or ContainerDef populated.
	ExtractAppOption(pass *analysis.Pass, app *AppAnnotation) (AppOptionMetadata, error)
}

// appOptionExtractorImpl implements AppOptionExtractor.
type appOptionExtractorImpl struct {
	annotation.Injectable[inject.Typed[AppOptionExtractor]]
}

// NewAppOptionExtractorImpl is a constructor for appOptionExtractorImpl.
//
// Generated by braider. DO NOT EDIT.
func NewAppOptionExtractorImpl() *appOptionExtractorImpl {
	return &appOptionExtractorImpl{}
}

// ExtractAppOption extracts the App option from the detected annotation.
func (e *appOptionExtractorImpl) ExtractAppOption(pass *analysis.Pass, app *AppAnnotation) (AppOptionMetadata, error) {
	if app.TypeArgExpr == nil {
		return AppOptionMetadata{IsDefault: true}, nil
	}

	typ := pass.TypesInfo.TypeOf(app.TypeArgExpr)
	if typ == nil {
		return AppOptionMetadata{IsDefault: true}, nil
	}

	// Check for AppDefault (app.Default) - includes method set check
	if e.isAppDefaultOption(typ) {
		return AppOptionMetadata{IsDefault: true}, nil
	}

	// Check for AppContainer (app.Container[T]) - named type with type args
	if containerDef := e.extractContainerDefinition(pass, typ, app.Pos); containerDef != nil {
		return AppOptionMetadata{ContainerDef: containerDef}, nil
	}

	// Check if the type implements AppContainer via method set (covers mixed options
	// and cases where the type checker expands interface embedding)
	if e.isAppContainerOption(typ) {
		// The type is a container option but we couldn't extract the inner type
		// through the Named type path. This can happen with mixed options.
		// Search embedded interfaces to find the Container[T] with type args.
		if containerDef := e.searchEmbeddedForContainerDef(pass, typ, app.Pos); containerDef != nil {
			return AppOptionMetadata{ContainerDef: containerDef}, nil
		}
		// Container option detected but could not extract struct type parameter.
		// This happens when Container has no type arguments (non-generic usage).
		return AppOptionMetadata{}, fmt.Errorf("app.Container detected but missing struct type parameter")
	}

	// Unknown option type
	return AppOptionMetadata{}, fmt.Errorf("unsupported App option type: %s", typ)
}

// isAppDefaultOption checks if the type is app.Default or implements AppDefault.
// Detection uses two strategies:
// 1. Named type check: direct name + package path matching (fast path)
// 2. Method set check: looks for _IsAppDefault method from internal/annotation (robust fallback)
func (e *appOptionExtractorImpl) isAppDefaultOption(typ types.Type) bool {
	if e.isAppDefaultOptionDirect(typ) {
		return true
	}
	// Check via method set (works for both Named types and interface types)
	if e.hasAppDefaultMethod(typ) {
		return true
	}
	return e.searchEmbeddedInterfacesForDefault(typ)
}

// isAppDefaultOptionDirect checks if the type directly is app.Default by name.
func (e *appOptionExtractorImpl) isAppDefaultOptionDirect(typ types.Type) bool {
	named, ok := typ.(*types.Named)
	if !ok {
		return false
	}

	obj := named.Obj()
	if obj == nil {
		return false
	}

	pkg := obj.Pkg()
	if pkg == nil {
		return false
	}

	return obj.Name() == "Default" && pkg.Path() == appOptionsPath
}

// hasAppDefaultMethod checks if the type's method set contains _IsAppDefault.
func (e *appOptionExtractorImpl) hasAppDefaultMethod(typ types.Type) bool {
	return e.hasMethodFromPackage(typ, "_IsAppDefault", internalAnnotationPath)
}

// hasAppContainerMethod checks if the type's method set contains _IsAppContainerMarker.
func (e *appOptionExtractorImpl) hasAppContainerMethod(typ types.Type) bool {
	return e.hasMethodFromPackage(typ, "_IsAppContainerMarker", internalAnnotationPath)
}

// hasMethodFromPackage checks if the type's interface method set includes a method
// with the given name whose return type is from the given package.
func (e *appOptionExtractorImpl) hasMethodFromPackage(typ types.Type, methodName, pkgPath string) bool {
	iface, ok := typ.Underlying().(*types.Interface)
	if !ok {
		return false
	}

	for i := 0; i < iface.NumMethods(); i++ {
		m := iface.Method(i)
		if m.Name() == methodName {
			// Verify the method's return type is from the expected package
			sig := m.Type().(*types.Signature)
			if sig.Results() != nil && sig.Results().Len() > 0 {
				retType := sig.Results().At(0).Type()
				if named, ok := retType.(*types.Named); ok {
					if p := named.Obj().Pkg(); p != nil && p.Path() == pkgPath {
						return true
					}
				}
			}
		}
	}
	return false
}

// searchEmbeddedInterfacesForDefault searches embedded interfaces for AppDefault.
func (e *appOptionExtractorImpl) searchEmbeddedInterfacesForDefault(typ types.Type) bool {
	iface, ok := typ.Underlying().(*types.Interface)
	if !ok {
		return false
	}

	for i := 0; i < iface.NumEmbeddeds(); i++ {
		embedded := iface.EmbeddedType(i)
		if e.isAppDefaultOptionDirect(embedded) {
			return true
		}
		if e.hasAppDefaultMethod(embedded) {
			return true
		}
		if e.searchEmbeddedInterfacesForDefault(embedded) {
			return true
		}
	}
	return false
}

// isAppContainerOption checks if the type is app.Container[T] or embeds it.
func (e *appOptionExtractorImpl) isAppContainerOption(typ types.Type) bool {
	if e.isAppContainerOptionDirect(typ) {
		return true
	}
	if e.hasAppContainerMethod(typ) {
		return true
	}
	return e.searchEmbeddedInterfacesForContainer(typ)
}

// isAppContainerOptionDirect checks if the type directly is app.Container by name.
func (e *appOptionExtractorImpl) isAppContainerOptionDirect(typ types.Type) bool {
	named, ok := typ.(*types.Named)
	if !ok {
		return false
	}

	obj := named.Obj()
	if obj == nil {
		return false
	}

	pkg := obj.Pkg()
	if pkg == nil {
		return false
	}

	return obj.Name() == "Container" && pkg.Path() == appOptionsPath
}

// searchEmbeddedInterfacesForContainer searches embedded interfaces for AppContainer.
func (e *appOptionExtractorImpl) searchEmbeddedInterfacesForContainer(typ types.Type) bool {
	iface, ok := typ.Underlying().(*types.Interface)
	if !ok {
		return false
	}

	for i := 0; i < iface.NumEmbeddeds(); i++ {
		embedded := iface.EmbeddedType(i)
		if e.isAppContainerOptionDirect(embedded) {
			return true
		}
		if e.hasAppContainerMethod(embedded) {
			return true
		}
		if e.searchEmbeddedInterfacesForContainer(embedded) {
			return true
		}
	}
	return false
}

// searchEmbeddedForContainerDef searches embedded interfaces for a Container[T] with extractable type args.
func (e *appOptionExtractorImpl) searchEmbeddedForContainerDef(
	pass *analysis.Pass, typ types.Type, pos token.Pos,
) *ContainerDefinition {
	iface, ok := typ.Underlying().(*types.Interface)
	if !ok {
		return nil
	}

	for i := 0; i < iface.NumEmbeddeds(); i++ {
		embedded := iface.EmbeddedType(i)
		if containerDef := e.extractContainerDefinition(pass, embedded, pos); containerDef != nil {
			return containerDef
		}
		// Recurse
		if containerDef := e.searchEmbeddedForContainerDef(pass, embedded, pos); containerDef != nil {
			return containerDef
		}
	}
	return nil
}

// extractContainerDefinition extracts a ContainerDefinition if the type is app.Container[T].
// Returns nil if the type is not a container type.
func (e *appOptionExtractorImpl) extractContainerDefinition(
	pass *analysis.Pass, typ types.Type, pos token.Pos,
) *ContainerDefinition {
	named, ok := typ.(*types.Named)
	if !ok {
		return nil
	}

	obj := named.Obj()
	if obj == nil {
		return nil
	}

	// Check if it's app.Container (package path + name check)
	pkg := obj.Pkg()
	if pkg == nil {
		return nil
	}

	if !(obj.Name() == "Container" && pkg.Path() == appOptionsPath) {
		return nil
	}

	// app.Container[T] has one type argument: the container struct type T
	typeArgs := named.TypeArgs()
	if typeArgs == nil || typeArgs.Len() == 0 {
		return nil
	}

	innerType := typeArgs.At(0)
	return e.buildContainerDefinition(pass, innerType, pos)
}

// buildContainerDefinition constructs a ContainerDefinition from the inner type T.
func (e *appOptionExtractorImpl) buildContainerDefinition(
	pass *analysis.Pass, innerType types.Type, pos token.Pos,
) *ContainerDefinition {
	def := &ContainerDefinition{
		Pos: pos,
	}

	// Determine if it's a named or anonymous struct type
	switch t := innerType.(type) {
	case *types.Named:
		// Named struct type
		structType, ok := t.Underlying().(*types.Struct)
		if !ok {
			return nil // Not a struct type
		}

		def.IsNamed = true
		def.NamedType = t
		def.StructType = structType

		typeObj := t.Obj()
		if typeObj != nil {
			def.LocalName = typeObj.Name()
			if p := typeObj.Pkg(); p != nil {
				def.PackagePath = p.Path()
				def.PackageName = p.Name()
				def.TypeName = p.Path() + "." + typeObj.Name()
			} else {
				def.TypeName = typeObj.Name()
			}
		}

	case *types.Struct:
		// Anonymous struct type
		def.IsNamed = false
		def.StructType = t

	default:
		return nil // Not a struct type
	}

	// Extract fields
	def.Fields = e.extractStructFields(pass, def.StructType)

	return def
}

// extractStructFields extracts ContainerField entries from a types.Struct.
func (e *appOptionExtractorImpl) extractStructFields(
	pass *analysis.Pass, structType *types.Struct,
) []ContainerField {
	fields := make([]ContainerField, 0, structType.NumFields())

	qualifier := types.RelativeTo(pass.Pkg)

	for i := 0; i < structType.NumFields(); i++ {
		field := structType.Field(i)
		tag := structType.Tag(i)

		// Extract braider struct tag value and detect whether the key exists
		braiderTag := ""
		hasBraiderTag := false
		if tag != "" {
			braiderTag = reflect.StructTag(tag).Get("braider")
			// reflect.StructTag.Get returns "" for both missing key and braider:"".
			// Detect presence by checking if "braider:" appears in the raw tag.
			hasBraiderTag = strings.Contains(tag, "braider:")
		}

		fields = append(fields, ContainerField{
			Name:          field.Name(),
			Type:          field.Type(),
			TypeString:    types.TypeString(field.Type(), qualifier),
			Tag:           braiderTag,
			HasBraiderTag: hasBraiderTag,
			Pos:           field.Pos(),
		})
	}

	return fields
}
