package detect

import (
	"fmt"
	"go/token"
	"go/types"
	"reflect"
	"strings"

	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"golang.org/x/tools/go/analysis"
)

// AppOptionExtractor extracts App option metadata from type arguments.
type AppOptionExtractor interface {
	// ExtractAppOption extracts the App option from the detected annotation.
	// Returns AppOptionMetadata with either IsDefault=true or ContainerDef populated.
	ExtractAppOption(pass *analysis.Pass, app *AppAnnotation) (AppOptionMetadata, error)
}

// appOptionExtractorImpl implements AppOptionExtractor.
type appOptionExtractorImpl struct {
	annotation.Injectable[inject.Typed[AppOptionExtractor]]
	markers *MarkerInterfaces
}

// NewAppOptionExtractorImpl is a constructor for appOptionExtractorImpl.
//
// Generated by braider. DO NOT EDIT.
func NewAppOptionExtractorImpl(markers *MarkerInterfaces) *appOptionExtractorImpl {
	return &appOptionExtractorImpl{
		markers: markers,
	}
}

// ExtractAppOption extracts the App option from the detected annotation.
func (e *appOptionExtractorImpl) ExtractAppOption(pass *analysis.Pass, app *AppAnnotation) (AppOptionMetadata, error) {
	if app.TypeArgExpr == nil {
		return AppOptionMetadata{IsDefault: true}, nil
	}

	typ := pass.TypesInfo.TypeOf(app.TypeArgExpr)
	if typ == nil {
		return AppOptionMetadata{IsDefault: true}, nil
	}

	// Check for AppDefault (app.Default)
	// Uses types.Implements with sealed marker interface.
	// types.Implements inherently handles embedded method sets, so mixed-in options are supported
	// without explicit recursion into embedded interfaces.
	if e.isAppDefaultOption(typ) {
		return AppOptionMetadata{IsDefault: true}, nil
	}

	// Check for AppContainer (app.Container[T])
	// Uses types.Implements with sealed marker interface.
	// types.Implements inherently handles embedded method sets, so mixed-in options are supported
	// without explicit recursion into embedded interfaces.
	if e.isAppContainerOption(typ) {
		// Try to extract the container definition from the type directly
		if containerDef := e.extractContainerDefinition(pass, typ, app.Pos); containerDef != nil {
			return AppOptionMetadata{ContainerDef: containerDef}, nil
		}
		// The type is a container option but we couldn't extract the inner type
		// through the Named type path. This can happen with mixed options.
		// Search embedded interfaces to find the Container[T] with type args.
		if containerDef := e.searchEmbeddedForContainerDef(pass, typ, app.Pos); containerDef != nil {
			return AppOptionMetadata{ContainerDef: containerDef}, nil
		}
		// Container option detected but could not extract struct type parameter.
		// This happens when Container has no type arguments (non-generic usage).
		return AppOptionMetadata{}, fmt.Errorf("app.Container detected but missing struct type parameter")
	}

	// Unknown option type
	return AppOptionMetadata{}, fmt.Errorf("unsupported App option type: %s", typ)
}

// isAppDefaultOption checks if the type implements AppDefault.
// Uses types.Implements with the sealed AppDefault marker interface.
func (e *appOptionExtractorImpl) isAppDefaultOption(typ types.Type) bool {
	return types.Implements(typ, e.markers.AppDefault)
}

// isAppContainerOption checks if the type implements AppContainer.
// Uses types.Implements with the sealed AppContainer marker interface.
func (e *appOptionExtractorImpl) isAppContainerOption(typ types.Type) bool {
	return types.Implements(typ, e.markers.AppContainer)
}

// searchEmbeddedForContainerDef searches embedded interfaces for a Container[T] with extractable type args.
func (e *appOptionExtractorImpl) searchEmbeddedForContainerDef(
	pass *analysis.Pass, typ types.Type, pos token.Pos,
) *ContainerDefinition {
	iface, ok := typ.Underlying().(*types.Interface)
	if !ok {
		return nil
	}

	for i := 0; i < iface.NumEmbeddeds(); i++ {
		embedded := iface.EmbeddedType(i)
		if containerDef := e.extractContainerDefinition(pass, embedded, pos); containerDef != nil {
			return containerDef
		}
		// Recurse
		if containerDef := e.searchEmbeddedForContainerDef(pass, embedded, pos); containerDef != nil {
			return containerDef
		}
	}
	return nil
}

// extractContainerDefinition extracts a ContainerDefinition if the type is app.Container[T].
// Uses types.Implements to identify the Container type, then extracts the struct type parameter.
// Returns nil if the type is not a container type.
func (e *appOptionExtractorImpl) extractContainerDefinition(
	pass *analysis.Pass, typ types.Type, pos token.Pos,
) *ContainerDefinition {
	named, ok := typ.(*types.Named)
	if !ok {
		return nil
	}

	// Check if this Named type implements AppContainer
	if !e.isAppContainerOption(typ) {
		return nil
	}

	// app.Container[T] has one type argument: the container struct type T
	typeArgs := named.TypeArgs()
	if typeArgs == nil || typeArgs.Len() == 0 {
		return nil
	}

	innerType := typeArgs.At(0)
	return e.buildContainerDefinition(pass, innerType, pos)
}

// buildContainerDefinition constructs a ContainerDefinition from the inner type T.
func (e *appOptionExtractorImpl) buildContainerDefinition(
	pass *analysis.Pass, innerType types.Type, pos token.Pos,
) *ContainerDefinition {
	def := &ContainerDefinition{
		Pos: pos,
	}

	// Determine if it's a named or anonymous struct type
	switch t := innerType.(type) {
	case *types.Named:
		// Named struct type
		structType, ok := t.Underlying().(*types.Struct)
		if !ok {
			return nil // Not a struct type
		}

		def.IsNamed = true
		def.NamedType = t
		def.StructType = structType

		typeObj := t.Obj()
		if typeObj != nil {
			def.LocalName = typeObj.Name()
			if p := typeObj.Pkg(); p != nil {
				def.PackagePath = p.Path()
				def.PackageName = p.Name()
				def.TypeName = p.Path() + "." + typeObj.Name()
			} else {
				def.TypeName = typeObj.Name()
			}
		}

	case *types.Struct:
		// Anonymous struct type
		def.IsNamed = false
		def.StructType = t

	default:
		return nil // Not a struct type
	}

	// Extract fields
	def.Fields = e.extractStructFields(pass, def.StructType)

	return def
}

// extractStructFields extracts ContainerField entries from a types.Struct.
func (e *appOptionExtractorImpl) extractStructFields(
	pass *analysis.Pass, structType *types.Struct,
) []ContainerField {
	fields := make([]ContainerField, 0, structType.NumFields())

	qualifier := types.RelativeTo(pass.Pkg)

	for i := 0; i < structType.NumFields(); i++ {
		field := structType.Field(i)
		tag := structType.Tag(i)

		// Extract braider struct tag value and detect whether the key exists
		braiderTag := ""
		hasBraiderTag := false
		if tag != "" {
			braiderTag = reflect.StructTag(tag).Get("braider")
			// reflect.StructTag.Get returns "" for both missing key and braider:"".
			// Detect presence by checking if "braider:" appears in the raw tag.
			hasBraiderTag = strings.Contains(tag, "braider:")
		}

		fields = append(fields, ContainerField{
			Name:          field.Name(),
			Type:          field.Type(),
			TypeString:    types.TypeString(field.Type(), qualifier),
			Tag:           braiderTag,
			HasBraiderTag: hasBraiderTag,
			Pos:           field.Pos(),
		})
	}

	return fields
}
