// Package detect provides detection capabilities for braider analyzer.
package detect

import (
	"go/ast"
	"go/types"

	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"golang.org/x/tools/go/analysis"
)

// AnnotationPath is the import path for the annotation package.
const AnnotationPath = "github.com/miyamo2/braider/pkg/annotation"

// InjectableTypeName is the type name for the Injectable[T] generic interface.
const InjectableTypeName = "Injectable"

// InjectDetector detects annotation.Injectable[T] embedding in structs.
type InjectDetector interface {
	// HasInjectAnnotation checks if a struct embeds annotation.Injectable[T].
	// Returns true if the struct has an embedded annotation.Injectable[T] field.
	HasInjectAnnotation(pass *analysis.Pass, st *ast.StructType) bool

	// FindInjectField returns the embedded Injectable field if present.
	// Returns nil if no Injectable embedding is found.
	FindInjectField(pass *analysis.Pass, st *ast.StructType) *ast.Field
}

// injectDetector is the default implementation of InjectDetector.
type injectDetector struct {
	annotation.Injectable[inject.Typed[InjectDetector]]
}

// NewInjectDetector is a constructor for injectDetector.
//
// Generated by braider. DO NOT EDIT.
func NewInjectDetector() *injectDetector {
	return &injectDetector{}
}

// HasInjectAnnotation checks if a struct embeds annotation.Injectable[T].
func (d *injectDetector) HasInjectAnnotation(pass *analysis.Pass, st *ast.StructType) bool {
	return d.FindInjectField(pass, st) != nil
}

// FindInjectField returns the embedded Injectable field if present.
func (d *injectDetector) FindInjectField(pass *analysis.Pass, st *ast.StructType) *ast.Field {
	if st.Fields == nil {
		return nil
	}

	for _, field := range st.Fields.List {
		// Check if it's an embedded field (no name)
		if len(field.Names) != 0 {
			continue
		}

		// Get the type of the field
		if !d.isInjectType(pass, field.Type) {
			continue
		}

		return field
	}

	return nil
}

// isInjectType checks if the given expression is the annotation.Injectable[T] type.
func (d *injectDetector) isInjectType(pass *analysis.Pass, expr ast.Expr) bool {
	// Use the type checker to get the type
	tv, ok := pass.TypesInfo.Types[expr]
	if !ok {
		// Try using TypeOf for expressions not in Types map
		t := pass.TypesInfo.TypeOf(expr)
		if t == nil {
			return false
		}
		return d.isNamedInjectType(pass, t)
	}

	return d.isNamedInjectType(pass, tv.Type)
}

// isNamedInjectType checks if the type is the annotation.Injectable[T] named type
// using types.Implements with the sealed marker interface.
func (d *injectDetector) isNamedInjectType(_ *analysis.Pass, t types.Type) bool {
	if markers := resolveMarkers(); markers != nil && markers.Injectable != nil {
		return types.Implements(t, markers.Injectable)
	}
	return false
}
