package detect

import (
	"fmt"
	"go/ast"
	"go/types"

	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"golang.org/x/tools/go/analysis"
)

// OptionExtractor extracts and validates type parameters from generic annotations.
type OptionExtractor interface {
	// ExtractInjectOptions extracts option metadata from Injectable[T] type parameter.
	// Returns OptionMetadata and error if validation fails (constraint violation, conflicts).
	ExtractInjectOptions(pass *analysis.Pass, fieldType ast.Expr, concreteType types.Type) (OptionMetadata, error)

	// ExtractProvideOptions extracts option metadata from Provider[T] type parameter.
	// Validates provider function return type compatibility with Typed[I] if present.
	ExtractProvideOptions(pass *analysis.Pass, callExpr *ast.CallExpr, providerFunc types.Type) (OptionMetadata, error)

	// ExtractVariableOptions extracts option metadata from Variable[T] type parameter.
	// Validates argument type compatibility with Typed[I] if present.
	// WithoutConstructor is not applicable to Variables and is never set.
	ExtractVariableOptions(pass *analysis.Pass, callExpr *ast.CallExpr, argumentType types.Type) (OptionMetadata, error)
}

// optionExtractorImpl implements OptionExtractor.
type optionExtractorImpl struct {
	annotation.Injectable[inject.Typed[OptionExtractor]]
	markers        *MarkerInterfaces
	namerValidator NamerValidator
}

// NewOptionExtractorImpl is a constructor for optionExtractorImpl.
//
// Generated by braider. DO NOT EDIT.
func NewOptionExtractorImpl(markers *MarkerInterfaces, namerValidator NamerValidator) *optionExtractorImpl {
	return &optionExtractorImpl{
		markers:        markers,
		namerValidator: namerValidator,
	}
}

// ExtractInjectOptions extracts options from Injectable[T] type parameter.
func (e *optionExtractorImpl) ExtractInjectOptions(
	pass *analysis.Pass, fieldType ast.Expr, concreteType types.Type,
) (OptionMetadata, error) {
	// Get the type of the field
	typ := pass.TypesInfo.TypeOf(fieldType)
	if typ == nil {
		return OptionMetadata{}, fmt.Errorf("cannot resolve type of field")
	}

	// Check if it's a generic type with type arguments
	named, ok := typ.(*types.Named)
	if !ok {
		// Not a generic type, check if it's the old Inject struct
		return OptionMetadata{IsDefault: true}, nil
	}

	// Get type arguments
	typeArgs := named.TypeArgs()
	if typeArgs == nil || typeArgs.Len() == 0 {
		// No type arguments, treat as default
		return OptionMetadata{IsDefault: true}, nil
	}

	// Extract first type argument (the option type)
	optionType := typeArgs.At(0)

	return e.extractMetadataFromOptionType(pass, optionType, concreteType)
}

// ExtractProvideOptions extracts options from Provider[T] type parameter.
func (e *optionExtractorImpl) ExtractProvideOptions(
	pass *analysis.Pass, callExpr *ast.CallExpr, providerFunc types.Type,
) (OptionMetadata, error) {
	// Get the type of the call expression (returns Provider[T])
	typ := pass.TypesInfo.TypeOf(callExpr)
	if typ == nil {
		return OptionMetadata{IsDefault: true}, nil
	}

	// Extract the Named type (Provider[T])
	named, ok := typ.(*types.Named)
	if !ok {
		return OptionMetadata{IsDefault: true}, nil
	}

	// Get type arguments of Provider[T]
	typeArgs := named.TypeArgs()
	if typeArgs == nil || typeArgs.Len() == 0 {
		return OptionMetadata{IsDefault: true}, nil
	}

	// Extract option type T
	optionType := typeArgs.At(0)

	// For Provide, concreteType is derived from the provider function return type
	var concreteType types.Type
	if sig, ok := providerFunc.(*types.Signature); ok {
		if sig.Results() != nil && sig.Results().Len() > 0 {
			concreteType = sig.Results().At(0).Type()
		}
	}

	return e.extractMetadataFromOptionType(pass, optionType, concreteType)
}

// ExtractVariableOptions extracts options from Variable[T] type parameter.
func (e *optionExtractorImpl) ExtractVariableOptions(
	pass *analysis.Pass, callExpr *ast.CallExpr, argumentType types.Type,
) (OptionMetadata, error) {
	// Get the type of the call expression (returns _variable which wraps T)
	typ := pass.TypesInfo.TypeOf(callExpr)
	if typ == nil {
		return OptionMetadata{IsDefault: true}, nil
	}

	// Extract the Named type (_variable[T])
	named, ok := typ.(*types.Named)
	if !ok {
		return OptionMetadata{IsDefault: true}, nil
	}

	// Get type arguments
	typeArgs := named.TypeArgs()
	if typeArgs == nil || typeArgs.Len() == 0 {
		return OptionMetadata{IsDefault: true}, nil
	}

	// Extract option type T
	optionType := typeArgs.At(0)

	// For Variable, concreteType is the argument expression's type
	return e.extractMetadataFromOptionType(pass, optionType, argumentType)
}

// extractMetadataFromOptionType extracts metadata from an option type parameter.
// Shared logic between ExtractInjectOptions, ExtractProvideOptions, and ExtractVariableOptions.
func (e *optionExtractorImpl) extractMetadataFromOptionType(
	pass *analysis.Pass, optionType types.Type, concreteType types.Type,
) (OptionMetadata, error) {
	metadata := OptionMetadata{}

	// Check for WithoutConstructor (check before Default)
	if e.isWithoutConstructorOption(pass, optionType) {
		metadata.WithoutConstructor = true
	} else if e.isDefaultOption(pass, optionType) {
		// Check for Default only if not WithoutConstructor
		metadata.IsDefault = true
	}

	// Check for Typed[I]
	if typedInterface := e.extractTypedInterface(pass, optionType); typedInterface != nil {
		iface, ok := typedInterface.Underlying().(*types.Interface)
		if !ok {
			return OptionMetadata{}, fmt.Errorf("Typed[I] requires an interface type, but got %s", typedInterface)
		}
		metadata.TypedInterface = typedInterface
		// Validate concrete type implements interface if both are available
		if concreteType != nil {
			if !types.Implements(concreteType, iface) {
				return OptionMetadata{}, fmt.Errorf(
					"concrete type %s does not implement interface %s",
					concreteType,
					typedInterface,
				)
			}
		}
	}

	// Check for Named[N]
	if namerType := e.extractNamerType(pass, optionType); namerType != nil {
		if e.namerValidator != nil {
			name, err := e.namerValidator.ExtractName(pass, namerType)
			if err != nil {
				return OptionMetadata{}, fmt.Errorf("failed to extract name from Namer: %w", err)
			}
			metadata.Name = name
		}
	}

	// Check for conflicting options
	if metadata.IsDefault && metadata.WithoutConstructor {
		return OptionMetadata{}, fmt.Errorf("conflicting options: cannot use both Default and WithoutConstructor")
	}

	return metadata, nil
}

// isDefaultOption checks if the type is inject.Default, provide.Default, or variable.Default.
// Uses types.Implements with sealed marker interfaces.
// types.Implements inherently handles embedded method sets, so mixed-in options are supported
// without explicit recursion into embedded interfaces.
func (e *optionExtractorImpl) isDefaultOption(_ *analysis.Pass, typ types.Type) bool {
	if e.markers == nil {
		return false
	}
	return (e.markers.InjectableDefault != nil && types.Implements(typ, e.markers.InjectableDefault)) ||
		(e.markers.ProviderDefault != nil && types.Implements(typ, e.markers.ProviderDefault)) ||
		(e.markers.VariableDefault != nil && types.Implements(typ, e.markers.VariableDefault))
}

// isWithoutConstructorOption checks if the type is inject.WithoutConstructor.
// Uses types.Implements with sealed marker interface.
// types.Implements inherently handles embedded method sets, so mixed-in options are supported
// without explicit recursion into embedded interfaces.
func (e *optionExtractorImpl) isWithoutConstructorOption(_ *analysis.Pass, typ types.Type) bool {
	if e.markers == nil {
		return false
	}
	return e.markers.InjectableWithoutCtor != nil && types.Implements(typ, e.markers.InjectableWithoutCtor)
}

// extractTypedInterface extracts the interface type from Typed[I] option.
// Supports both direct named types and interface embedded types (mixed-in options).
func (e *optionExtractorImpl) extractTypedInterface(pass *analysis.Pass, typ types.Type) types.Type {
	if result := e.extractTypedInterfaceDirect(pass, typ); result != nil {
		return result
	}
	return e.searchEmbeddedInterfacesTyped(typ, func(t types.Type) types.Type {
		return e.extractTypedInterfaceDirect(pass, t)
	})
}

// extractTypedInterfaceDirect extracts Typed[I] from a direct named type.
// Uses types.Implements with sealed marker interfaces.
func (e *optionExtractorImpl) extractTypedInterfaceDirect(_ *analysis.Pass, typ types.Type) types.Type {
	named, ok := typ.(*types.Named)
	if !ok {
		return nil
	}

	if e.markers == nil {
		return nil
	}

	isTyped := (e.markers.InjectableTyped != nil && types.Implements(typ, e.markers.InjectableTyped)) ||
		(e.markers.ProviderTyped != nil && types.Implements(typ, e.markers.ProviderTyped)) ||
		(e.markers.VariableTyped != nil && types.Implements(typ, e.markers.VariableTyped))
	if !isTyped {
		return nil
	}

	typeArgs := named.TypeArgs()
	if typeArgs == nil || typeArgs.Len() == 0 {
		return nil
	}

	return typeArgs.At(0)
}

// extractNamerType extracts the Namer type from Named[N] option.
// Supports both direct named types and interface embedded types (mixed-in options).
func (e *optionExtractorImpl) extractNamerType(pass *analysis.Pass, typ types.Type) types.Type {
	if result := e.extractNamerTypeDirect(pass, typ); result != nil {
		return result
	}
	return e.searchEmbeddedInterfacesTyped(typ, func(t types.Type) types.Type {
		return e.extractNamerTypeDirect(pass, t)
	})
}

// extractNamerTypeDirect extracts Named[N] from a direct named type.
// Uses types.Implements with sealed marker interfaces.
func (e *optionExtractorImpl) extractNamerTypeDirect(_ *analysis.Pass, typ types.Type) types.Type {
	named, ok := typ.(*types.Named)
	if !ok {
		return nil
	}

	if e.markers == nil {
		return nil
	}

	isNamed := (e.markers.InjectableNamed != nil && types.Implements(typ, e.markers.InjectableNamed)) ||
		(e.markers.ProviderNamed != nil && types.Implements(typ, e.markers.ProviderNamed)) ||
		(e.markers.VariableNamed != nil && types.Implements(typ, e.markers.VariableNamed))
	if !isNamed {
		return nil
	}

	typeArgs := named.TypeArgs()
	if typeArgs == nil || typeArgs.Len() == 0 {
		return nil
	}

	return typeArgs.At(0)
}

// searchEmbeddedInterfacesTyped recursively searches embedded interfaces for a type-returning match.
func (e *optionExtractorImpl) searchEmbeddedInterfacesTyped(
	typ types.Type, extractor func(types.Type) types.Type,
) types.Type {
	iface, ok := typ.Underlying().(*types.Interface)
	if !ok {
		return nil
	}

	for i := 0; i < iface.NumEmbeddeds(); i++ {
		embedded := iface.EmbeddedType(i)
		if result := extractor(embedded); result != nil {
			return result
		}
		// Recurse into embedded interfaces
		if result := e.searchEmbeddedInterfacesTyped(embedded, extractor); result != nil {
			return result
		}
	}
	return nil
}
