package detect

import (
	"go/ast"
	"go/types"

	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/ast/inspector"
)

// ProvideTypeName is the type name for the Provide annotation.
const ProvideTypeName = "Provide"

// ProviderCandidate represents a detected provider from annotation.Provide[T](fn) call.
type ProviderCandidate struct {
	// CallExpr is the annotation.Provide[T](fn) call expression
	CallExpr *ast.CallExpr
	// ProviderFunc is the fn argument expression
	ProviderFunc ast.Expr
	// ProviderFuncSig is fn's type signature
	ProviderFuncSig *types.Signature
	// ProviderFuncName is the function name (e.g., "NewUserRepository")
	ProviderFuncName string
	// ProviderFuncPkgPath is the import path of the provider function's package
	ProviderFuncPkgPath string
	// ProviderFuncPkgName is the package name of the provider function's package
	ProviderFuncPkgName string
	// ReturnType is the first return type of the provider function
	ReturnType types.Type
	// ReturnTypeName is the local name of the return type (e.g., "userRepository")
	ReturnTypeName string
	// PackagePath is the import path of the return type's package
	PackagePath string
	// Implements contains interface types the return type implements
	Implements []string
}

// ProvideCallDetector identifies annotation.Provide[T](fn) call expressions.
type ProvideCallDetector interface {
	// DetectProviders returns all annotation.Provide[T](fn) calls in the package.
	DetectProviders(pass *analysis.Pass) []ProviderCandidate

	// DetectImplementedInterfaces returns interface types the given type implements.
	DetectImplementedInterfaces(pass *analysis.Pass, namedType *types.Named) []string
}

// provideCallDetector is the default implementation of ProvideCallDetector.
type provideCallDetector struct {
	annotation.Injectable[inject.Typed[ProvideCallDetector]]
	markers *MarkerInterfaces
}

// NewProvideCallDetector is a constructor for provideCallDetector.
//
// Generated by braider. DO NOT EDIT.
func NewProvideCallDetector(markers *MarkerInterfaces) *provideCallDetector {
	return &provideCallDetector{
		markers: markers,
	}
}

// DetectProviders returns all annotation.Provide[T](fn) calls in the package.
func (d *provideCallDetector) DetectProviders(pass *analysis.Pass) []ProviderCandidate {
	var candidates []ProviderCandidate

	insp := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)

	nodeFilter := []ast.Node{
		(*ast.GenDecl)(nil),
	}

	insp.Preorder(
		nodeFilter, func(n ast.Node) {
			genDecl := n.(*ast.GenDecl)
			candidates = d.processGenDecl(pass, genDecl, candidates)
		},
	)

	return candidates
}

// processGenDecl processes a GenDecl and looks for var _ = annotation.Provide[T](fn) patterns.
func (d *provideCallDetector) processGenDecl(
	pass *analysis.Pass, genDecl *ast.GenDecl, candidates []ProviderCandidate,
) []ProviderCandidate {
	for _, spec := range genDecl.Specs {
		valueSpec, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}

		for _, value := range valueSpec.Values {
			callExpr, ok := value.(*ast.CallExpr)
			if !ok {
				continue
			}

			if !d.isProvideCall(pass, callExpr) {
				continue
			}

			candidate := d.extractCandidate(pass, callExpr)
			if candidate != nil {
				candidates = append(candidates, *candidate)
			}
		}
	}
	return candidates
}

// isProvideCall checks if a call expression is annotation.Provide[T](fn).
func (d *provideCallDetector) isProvideCall(pass *analysis.Pass, callExpr *ast.CallExpr) bool {
	// The function part is annotation.Provide[T] which is an IndexExpr wrapping a SelectorExpr
	// Pattern: *ast.IndexExpr { X: *ast.SelectorExpr { Sel: "Provide" } }
	var selExpr *ast.SelectorExpr

	switch fun := callExpr.Fun.(type) {
	case *ast.IndexExpr:
		// annotation.Provide[T](fn) - single type parameter
		sel, ok := fun.X.(*ast.SelectorExpr)
		if !ok {
			return false
		}
		selExpr = sel
	case *ast.SelectorExpr:
		// annotation.Provide(fn) - no type parameter (non-generic)
		selExpr = fun
	default:
		return false
	}

	// Check selector name is "Provide"
	if selExpr.Sel.Name != ProvideTypeName {
		return false
	}

	// Check the call's return type implements the Provider marker interface
	typ := pass.TypesInfo.TypeOf(callExpr)
	if typ == nil {
		return false
	}

	return types.Implements(typ, d.markers.Provider)
}

// extractCandidate extracts a ProviderCandidate from a validated Provide[T](fn) call.
func (d *provideCallDetector) extractCandidate(pass *analysis.Pass, callExpr *ast.CallExpr) *ProviderCandidate {
	if len(callExpr.Args) == 0 {
		return nil
	}

	providerFuncExpr := callExpr.Args[0]

	// Get the type of the provider function argument
	providerFuncType := pass.TypesInfo.TypeOf(providerFuncExpr)
	if providerFuncType == nil {
		return nil
	}

	sig, ok := providerFuncType.(*types.Signature)
	if !ok {
		return nil
	}

	// Extract function name
	funcName := d.extractFuncName(providerFuncExpr)

	// Extract provider function's package
	providerFuncPkgPath, providerFuncPkgName := d.extractFuncPkg(pass, providerFuncExpr)

	// Extract return type
	var returnType types.Type
	var returnTypeName string
	if sig.Results() != nil && sig.Results().Len() > 0 {
		returnType = sig.Results().At(0).Type()
		returnTypeName = d.extractReturnTypeName(returnType)
	}

	// Detect implemented interfaces
	var implements []string
	if returnType != nil {
		implements = d.detectImplementedInterfacesFromType(pass, returnType)
	}

	// Derive PackagePath from return type's actual package
	var packagePath string
	if returnType != nil {
		rt := returnType
		if ptr, ok := rt.(*types.Pointer); ok {
			rt = ptr.Elem()
		}
		if named, ok := rt.(*types.Named); ok {
			if pkg := named.Obj().Pkg(); pkg != nil {
				packagePath = pkg.Path()
			}
		}
	}
	if packagePath == "" {
		packagePath = pass.Pkg.Path()
	}

	return &ProviderCandidate{
		CallExpr:            callExpr,
		ProviderFunc:        providerFuncExpr,
		ProviderFuncSig:     sig,
		ProviderFuncName:    funcName,
		ProviderFuncPkgPath: providerFuncPkgPath,
		ProviderFuncPkgName: providerFuncPkgName,
		ReturnType:          returnType,
		ReturnTypeName:      returnTypeName,
		PackagePath:         packagePath,
		Implements:          implements,
	}
}

// extractFuncPkg extracts the provider function's package path and name.
// For local functions (*ast.Ident), uses pass.TypesInfo to resolve the object's package.
// For qualified functions (*ast.SelectorExpr), resolves from the selector.
// Falls back to pass.Pkg if resolution fails.
func (d *provideCallDetector) extractFuncPkg(pass *analysis.Pass, expr ast.Expr) (string, string) {
	switch e := expr.(type) {
	case *ast.Ident:
		if obj := pass.TypesInfo.Uses[e]; obj != nil {
			if pkg := obj.Pkg(); pkg != nil {
				return pkg.Path(), pkg.Name()
			}
		}
	case *ast.SelectorExpr:
		if obj := pass.TypesInfo.Uses[e.Sel]; obj != nil {
			if pkg := obj.Pkg(); pkg != nil {
				return pkg.Path(), pkg.Name()
			}
		}
	}
	return pass.Pkg.Path(), pass.Pkg.Name()
}

// extractFuncName extracts the function name from a function expression.
func (d *provideCallDetector) extractFuncName(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return e.Sel.Name
	default:
		return ""
	}
}

// extractReturnTypeName extracts the local type name from a return type.
func (d *provideCallDetector) extractReturnTypeName(t types.Type) string {
	// Dereference pointer type
	if ptr, ok := t.(*types.Pointer); ok {
		t = ptr.Elem()
	}

	if named, ok := t.(*types.Named); ok {
		return named.Obj().Name()
	}

	return ""
}

// detectImplementedInterfacesFromType detects interfaces implemented by the given type.
func (d *provideCallDetector) detectImplementedInterfacesFromType(pass *analysis.Pass, returnType types.Type) []string {
	return findImplementedInterfacesFromType(pass, returnType)
}

// DetectImplementedInterfaces returns interface types the given named type implements.
func (d *provideCallDetector) DetectImplementedInterfaces(pass *analysis.Pass, namedType *types.Named) []string {
	return findImplementedInterfaces(pass, namedType)
}
