package graph

import (
	"go/token"
	"go/types"
	"strings"

	"github.com/miyamo2/braider/internal/detect"
	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
)

// ContainerValidator validates container struct definitions against the dependency graph.
type ContainerValidator interface {
	// Validate checks all container fields are resolvable.
	// Returns a list of validation errors (empty if valid).
	Validate(
		containerDef *detect.ContainerDefinition,
		g *Graph,
	) []ContainerValidationError
}

// ContainerValidationError represents a single container validation error.
type ContainerValidationError struct {
	Pos       token.Pos
	FieldName string
	Message   string
}

// containerValidatorImpl implements ContainerValidator.
type containerValidatorImpl struct {
	annotation.Injectable[inject.Typed[ContainerValidator]]
	interfaceRegistry *InterfaceRegistry
}

// NewContainerValidatorImpl is a constructor for containerValidatorImpl.
//
// Generated by braider. DO NOT EDIT.
func NewContainerValidatorImpl(interfaceRegistry *InterfaceRegistry) *containerValidatorImpl {
	return &containerValidatorImpl{
		interfaceRegistry: interfaceRegistry,
	}
}

// Validate checks all container fields are resolvable against the dependency graph.
func (v *containerValidatorImpl) Validate(
	containerDef *detect.ContainerDefinition,
	g *Graph,
) []ContainerValidationError {
	if containerDef == nil || g == nil {
		return nil
	}

	// Defensive: ensure StructType is actually a struct
	if containerDef.StructType == nil {
		return []ContainerValidationError{
			{
				Pos:     containerDef.Pos,
				Message: "container type parameter must be a struct type",
			},
		}
	}

	var errors []ContainerValidationError

	for _, field := range containerDef.Fields {
		if errs := v.validateField(field, g); len(errs) > 0 {
			errors = append(errors, errs...)
		}
	}

	return errors
}

// validateField validates a single container field against the graph.
func (v *containerValidatorImpl) validateField(
	field detect.ContainerField,
	g *Graph,
) []ContainerValidationError {
	// Check braider tag constraints
	if field.HasBraiderTag {
		if field.Tag == "-" {
			return []ContainerValidationError{
				{
					Pos:       field.Pos,
					FieldName: field.Name,
					Message:   `braider:"-" tag is not permitted in container struct fields`,
				},
			}
		}
		if field.Tag == "" {
			return []ContainerValidationError{
				{
					Pos:       field.Pos,
					FieldName: field.Name,
					Message:   `braider:"" empty tag is not permitted, use braider:"name" to specify a dependency name`,
				},
			}
		}
		// Resolve by name
		return v.validateNamedField(field, g)
	}

	// No braider tag: resolve by type
	return v.validateTypedField(field, g)
}

// validateTypedField validates a field resolved by type (no braider tag).
func (v *containerValidatorImpl) validateTypedField(
	field detect.ContainerField,
	g *Graph,
) []ContainerValidationError {
	fieldTypeName := fullyQualifiedTypeName(field.Type)

	// Check if the field type is an interface
	if _, isIface := field.Type.Underlying().(*types.Interface); isIface {
		return v.validateInterfaceField(field, fieldTypeName, g)
	}

	// Concrete type: look for matching graph nodes
	var matches []string
	for nodeKey, node := range g.Nodes {
		if node.TypeName == fieldTypeName {
			matches = append(matches, nodeKey)
		}
	}

	if len(matches) == 0 {
		// Also try pointer-stripped form
		stripped := strings.TrimPrefix(fieldTypeName, "*")
		for nodeKey, node := range g.Nodes {
			if node.TypeName == stripped {
				matches = append(matches, nodeKey)
			}
		}
	}

	if len(matches) == 0 {
		return []ContainerValidationError{
			{
				Pos:       field.Pos,
				FieldName: field.Name,
				Message:   "no matching dependency found in the graph",
			},
		}
	}

	if len(matches) > 1 {
		return []ContainerValidationError{
			{
				Pos:       field.Pos,
				FieldName: field.Name,
				Message:   "ambiguous: multiple named registrations match this type, use braider:\"name\" tag to disambiguate",
			},
		}
	}

	return nil
}

// validateInterfaceField validates an interface-typed field using the InterfaceRegistry.
func (v *containerValidatorImpl) validateInterfaceField(
	field detect.ContainerField,
	ifaceTypeName string,
	g *Graph,
) []ContainerValidationError {
	if v.interfaceRegistry == nil {
		return []ContainerValidationError{
			{
				Pos:       field.Pos,
				FieldName: field.Name,
				Message:   "no matching dependency found in the graph (interface registry unavailable)",
			},
		}
	}

	implTypeName, err := v.interfaceRegistry.Resolve(ifaceTypeName)
	if err != nil {
		if ambErr, ok := err.(*AmbiguousImplementationError); ok {
			return []ContainerValidationError{
				{
					Pos:       field.Pos,
					FieldName: field.Name,
					Message:   ambErr.Error(),
				},
			}
		}
		return []ContainerValidationError{
			{
				Pos:       field.Pos,
				FieldName: field.Name,
				Message:   "no matching dependency found in the graph",
			},
		}
	}

	// Verify the resolved implementation exists in the graph
	found := false
	for _, node := range g.Nodes {
		if node.TypeName == implTypeName {
			found = true
			break
		}
	}
	if !found {
		return []ContainerValidationError{
			{
				Pos:       field.Pos,
				FieldName: field.Name,
				Message:   "no matching dependency found in the graph",
			},
		}
	}

	return nil
}

// validateNamedField validates a field resolved by braider tag name.
func (v *containerValidatorImpl) validateNamedField(
	field detect.ContainerField,
	g *Graph,
) []ContainerValidationError {
	fieldTypeName := fullyQualifiedTypeName(field.Type)

	// Search for a node matching both type and name via composite key
	compositeKey := fieldTypeName + "#" + field.Tag
	if _, ok := g.Nodes[compositeKey]; ok {
		return nil
	}

	// Try pointer-stripped form
	stripped := strings.TrimPrefix(fieldTypeName, "*")
	compositeKey = stripped + "#" + field.Tag
	if _, ok := g.Nodes[compositeKey]; ok {
		return nil
	}

	// Try interface resolution for the type
	if _, isIface := field.Type.Underlying().(*types.Interface); isIface && v.interfaceRegistry != nil {
		implTypeName, err := v.interfaceRegistry.Resolve(fieldTypeName)
		if err == nil {
			compositeKey = implTypeName + "#" + field.Tag
			if _, ok := g.Nodes[compositeKey]; ok {
				return nil
			}
		}
	}

	return []ContainerValidationError{
		{
			Pos:       field.Pos,
			FieldName: field.Name,
			Message:   "no matching named dependency found in the graph",
		},
	}
}

// fullyQualifiedTypeName returns the fully qualified name of a type,
// stripping pointer indirection.
func fullyQualifiedTypeName(t types.Type) string {
	// Unwrap pointer
	for {
		ptr, ok := t.(*types.Pointer)
		if !ok {
			break
		}
		t = ptr.Elem()
	}

	switch typ := t.(type) {
	case *types.Named:
		obj := typ.Obj()
		if obj == nil {
			return t.String()
		}
		pkg := obj.Pkg()
		if pkg == nil {
			return obj.Name()
		}
		return pkg.Path() + "." + obj.Name()
	default:
		return t.String()
	}
}
