package graph

import (
	"fmt"
	"go/types"
	"strings"
	"unicode"

	"github.com/miyamo2/braider/internal/detect"
	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
)

// ContainerResolver resolves container fields to dependency graph nodes.
type ContainerResolver interface {
	ResolveFields(
		containerDef *detect.ContainerDefinition,
		g *Graph,
	) ([]detect.ResolvedContainerField, error)
}

// containerResolverImpl implements ContainerResolver.
type containerResolverImpl struct {
	annotation.Injectable[inject.Typed[ContainerResolver]]
	interfaceRegistry *InterfaceRegistry
}

// NewContainerResolverImpl is a constructor for containerResolverImpl.
//
// Generated by braider. DO NOT EDIT.
func NewContainerResolverImpl(interfaceRegistry *InterfaceRegistry) *containerResolverImpl {
	return &containerResolverImpl{
		interfaceRegistry: interfaceRegistry,
	}
}

// ResolveFields resolves each container field to its dependency graph node.
func (r *containerResolverImpl) ResolveFields(
	containerDef *detect.ContainerDefinition,
	g *Graph,
) ([]detect.ResolvedContainerField, error) {
	resolved := make([]detect.ResolvedContainerField, 0, len(containerDef.Fields))

	for _, field := range containerDef.Fields {
		rf, err := r.resolveField(field, g)
		if err != nil {
			return nil, fmt.Errorf("field %s: %w", field.Name, err)
		}
		resolved = append(resolved, rf)
	}

	return resolved, nil
}

// resolveField resolves a single container field to its graph node.
func (r *containerResolverImpl) resolveField(
	field detect.ContainerField,
	g *Graph,
) (detect.ResolvedContainerField, error) {
	if field.HasBraiderTag && field.Tag != "" {
		// Resolve by name
		return r.resolveNamedField(field, g)
	}

	// Resolve by type
	return r.resolveTypedField(field, g)
}

// resolveTypedField resolves a field by matching its type against graph nodes.
func (r *containerResolverImpl) resolveTypedField(
	field detect.ContainerField,
	g *Graph,
) (detect.ResolvedContainerField, error) {
	fieldTypeName := fullyQualifiedTypeName(field.Type)

	// Check if the field type is an interface
	if _, isIface := field.Type.Underlying().(*types.Interface); isIface {
		return r.resolveInterfaceField(field, fieldTypeName, g)
	}

	// Concrete type: find matching node
	for nodeKey, node := range g.Nodes {
		if node.TypeName == fieldTypeName {
			return detect.ResolvedContainerField{
				FieldName: field.Name,
				NodeKey:   nodeKey,
				VarName:   deriveVarName(node),
			}, nil
		}
	}

	// Try pointer-stripped form
	stripped := strings.TrimPrefix(fieldTypeName, "*")
	for nodeKey, node := range g.Nodes {
		if node.TypeName == stripped {
			return detect.ResolvedContainerField{
				FieldName: field.Name,
				NodeKey:   nodeKey,
				VarName:   deriveVarName(node),
			}, nil
		}
	}

	return detect.ResolvedContainerField{}, fmt.Errorf("no matching dependency for type %s", fieldTypeName)
}

// resolveInterfaceField resolves an interface-typed field through the InterfaceRegistry.
func (r *containerResolverImpl) resolveInterfaceField(
	field detect.ContainerField,
	ifaceTypeName string,
	g *Graph,
) (detect.ResolvedContainerField, error) {
	if r.interfaceRegistry == nil {
		return detect.ResolvedContainerField{}, fmt.Errorf("interface registry unavailable")
	}

	implTypeName, err := r.interfaceRegistry.Resolve(ifaceTypeName)
	if err != nil {
		return detect.ResolvedContainerField{}, err
	}

	for nodeKey, node := range g.Nodes {
		if node.TypeName == implTypeName {
			return detect.ResolvedContainerField{
				FieldName: field.Name,
				NodeKey:   nodeKey,
				VarName:   deriveVarName(node),
			}, nil
		}
	}

	return detect.ResolvedContainerField{}, fmt.Errorf("resolved type %s not found in graph", implTypeName)
}

// resolveNamedField resolves a field by its braider tag name (composite key).
func (r *containerResolverImpl) resolveNamedField(
	field detect.ContainerField,
	g *Graph,
) (detect.ResolvedContainerField, error) {
	fieldTypeName := fullyQualifiedTypeName(field.Type)

	// Try direct composite key
	compositeKey := fieldTypeName + "#" + field.Tag
	if node, ok := g.Nodes[compositeKey]; ok {
		return detect.ResolvedContainerField{
			FieldName: field.Name,
			NodeKey:   compositeKey,
			VarName:   deriveVarName(node),
		}, nil
	}

	// Try pointer-stripped form
	stripped := strings.TrimPrefix(fieldTypeName, "*")
	compositeKey = stripped + "#" + field.Tag
	if node, ok := g.Nodes[compositeKey]; ok {
		return detect.ResolvedContainerField{
			FieldName: field.Name,
			NodeKey:   compositeKey,
			VarName:   deriveVarName(node),
		}, nil
	}

	// Try interface resolution
	if _, isIface := field.Type.Underlying().(*types.Interface); isIface && r.interfaceRegistry != nil {
		implTypeName, err := r.interfaceRegistry.Resolve(fieldTypeName)
		if err == nil {
			compositeKey = implTypeName + "#" + field.Tag
			if node, ok := g.Nodes[compositeKey]; ok {
				return detect.ResolvedContainerField{
					FieldName: field.Name,
					NodeKey:   compositeKey,
					VarName:   deriveVarName(node),
				}, nil
			}
		}
	}

	return detect.ResolvedContainerField{}, fmt.Errorf("no matching named dependency %q for type %s", field.Tag, fieldTypeName)
}

// deriveVarName derives the variable name for a graph node.
// Uses the node's Name if set, otherwise derives from TypeName using lowerCamelCase.
func deriveVarName(node *Node) string {
	if node.Name != "" {
		return node.Name
	}
	return deriveFieldNameFromType(node.TypeName)
}

// deriveFieldNameFromType extracts the local type name from a fully qualified
// name and converts it to lowerCamelCase for use as a variable name.
// This duplicates generate.DeriveFieldName to avoid an import cycle.
func deriveFieldNameFromType(typeName string) string {
	parts := strings.Split(typeName, ".")
	localName := parts[len(parts)-1]
	if localName == "" {
		return "field"
	}
	return toLowerCamelCase(localName)
}

// toLowerCamelCase converts a name to lowerCamelCase.
// Duplicated from generate.ToLowerCamelCase to avoid an import cycle.
func toLowerCamelCase(name string) string {
	if name == "" {
		return ""
	}
	runes := []rune(name)
	i := 0
	for i < len(runes) && unicode.IsUpper(runes[i]) {
		i++
	}
	if i == 0 {
		return name
	}
	if i == len(runes) {
		return strings.ToLower(name)
	}
	if i == 1 {
		runes[0] = unicode.ToLower(runes[0])
		return string(runes)
	}
	for j := 0; j < i-1; j++ {
		runes[j] = unicode.ToLower(runes[j])
	}
	return string(runes)
}
