package generate

import (
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"regexp"
	"strings"

	"github.com/miyamo2/braider/internal/detect"
	"github.com/miyamo2/braider/internal/graph"
	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"golang.org/x/tools/go/analysis"
)

// hashCommentRe is a compiled regular expression for extracting hash markers from comments.
// Cached at package level to avoid repeated compilation.
var hashCommentRe = regexp.MustCompile(`//\s*braider:hash:\s*([a-f0-9]+)`)

// GeneratedBootstrap represents the generated bootstrap code and metadata.
type GeneratedBootstrap struct {
	DependencyVar string       // IIFE code defining the dependency variable
	MainReference string       // Optional "_ = dependency" statement for main
	Imports       []ImportInfo // Required import paths with aliases
	Hash          string       // Hash marker for idempotency
}

// BootstrapGenerator generates bootstrap code for the DI system.
type BootstrapGenerator interface {
	GenerateBootstrap(pass *analysis.Pass, g *graph.Graph, sortedTypes []string) (*GeneratedBootstrap, error)
	GenerateContainerBootstrap(pass *analysis.Pass, g *graph.Graph, sortedTypes []string, containerDef *detect.ContainerDefinition, resolvedFields []detect.ResolvedContainerField) (*GeneratedBootstrap, error)
	CheckBootstrapCurrent(pass *analysis.Pass, existing *ast.GenDecl, g *graph.Graph) bool
	CheckContainerBootstrapCurrent(pass *analysis.Pass, existing *ast.GenDecl, g *graph.Graph, containerDef *detect.ContainerDefinition) bool
	DetectExistingBootstrap(pass *analysis.Pass) *ast.GenDecl
}

// bootstrapGenerator is the default implementation.
type bootstrapGenerator struct {
	annotation.Injectable[inject.Typed[BootstrapGenerator]]
}

// NewBootstrapGenerator is a constructor for bootstrapGenerator.
//
// Generated by braider. DO NOT EDIT.
func NewBootstrapGenerator() *bootstrapGenerator {
	return &bootstrapGenerator{}
}

// GenerateBootstrap generates the complete bootstrap code.
func (bg *bootstrapGenerator) GenerateBootstrap(
	pass *analysis.Pass,
	g *graph.Graph,
	sortedTypes []string,
) (*GeneratedBootstrap, error) {
	if g == nil {
		return nil, fmt.Errorf("nil dependency graph")
	}

	// Compute hash for idempotency (works even with empty graph)
	hash := ComputeGraphHash(g)

	// Detect existing aliases from the target file
	// Find the file containing App annotation or existing bootstrap
	var targetFile *ast.File
	existingBootstrap := bg.DetectExistingBootstrap(pass)
	if existingBootstrap != nil {
		// Find file containing existing bootstrap
		for _, file := range pass.Files {
			for _, decl := range file.Decls {
				if decl == existingBootstrap {
					targetFile = file
					break
				}
			}
			if targetFile != nil {
				break
			}
		}
	}
	// If no existing bootstrap, use the first file (typically main.go)
	if targetFile == nil && len(pass.Files) > 0 {
		targetFile = pass.Files[0]
	}
	existingAliases := detectExistingAliases(targetFile)

	// Collect imports
	currentPackage := pass.Pkg.Path()
	currentPkgName := pass.Pkg.Name()
	imports, aliasMap := CollectImports(g, currentPackage, currentPkgName, existingAliases)

	// Track field names
	fieldNames := make(map[string]string) // typeName -> fieldName

	// Phase 1: Build struct fields for Inject and Provide nodes (IsField=true)
	var astStructFields []*ast.Field
	var fieldNameList []string // parallel to astStructFields

	for _, typeName := range sortedTypes {
		node := g.Nodes[typeName]
		if node == nil || !node.IsField {
			continue
		}

		fieldName := node.Name
		if fieldName == "" {
			fieldName = DeriveFieldName(typeName)
		}
		fieldNames[typeName] = fieldName

		typeExpr := bg.buildNodeTypeExpr(node, currentPackage, currentPkgName, aliasMap)
		astStructFields = append(astStructFields, &ast.Field{Names: []*ast.Ident{{Name: fieldName}}, Type: typeExpr})
		fieldNameList = append(fieldNameList, fieldName)
	}

	// Build a set of node keys that are depended upon by other nodes.
	dependedUpon := make(map[string]struct{})
	for _, node := range g.Nodes {
		for _, dep := range node.Dependencies {
			dependedUpon[dep] = struct{}{}
		}
	}

	// Phase 2: Generate initialization statements as AST
	var initStmts []ast.Stmt
	for _, typeName := range sortedTypes {
		node := g.Nodes[typeName]
		if node == nil {
			continue
		}

		varName := bg.resolveVarName(node, typeName, fieldNames)

		// Variable node: emit expression assignment
		if node.ExpressionText != "" {
			expressionText := bg.resolveExpressionText(node, currentPackage, currentPkgName, aliasMap)
			exprAST := parseExprString(expressionText)
			if _, ok := dependedUpon[typeName]; ok {
				initStmts = append(initStmts, astShortVar(varName, exprAST))
			} else {
				initStmts = append(initStmts, astBlankAssign(exprAST))
			}
			continue
		}

		// Provider/Injector node: constructor call
		if len(node.ConstructorName) == 0 {
			return nil, fmt.Errorf("injectable struct %s requires a constructor", typeName)
		}

		callExpr := bg.buildConstructorCallExpr(node, g, fieldNames, currentPkgName)
		initStmts = append(initStmts, astShortVar(varName, callExpr))
	}

	// Phase 3: Build IIFE as AST
	// struct type for return type (used in func signature)
	returnStructType := astStructType(astStructFields...)

	// Build duplicate struct type for the return composite literal
	var returnLitFields []*ast.Field
	for _, typeName := range sortedTypes {
		node := g.Nodes[typeName]
		if node == nil || !node.IsField {
			continue
		}
		fieldName := fieldNames[typeName]
		typeExpr := bg.buildNodeTypeExpr(node, currentPackage, currentPkgName, aliasMap)
		returnLitFields = append(returnLitFields, &ast.Field{Names: []*ast.Ident{{Name: fieldName}}, Type: typeExpr})
	}
	returnLitStructType := astStructType(returnLitFields...)

	// Build return composite literal: struct{...}{field: field, ...}
	var returnElts []ast.Expr
	for _, fieldName := range fieldNameList {
		returnElts = append(returnElts, &ast.KeyValueExpr{Key: &ast.Ident{Name: fieldName}, Value: &ast.Ident{Name: fieldName}})
	}
	returnLit := &ast.CompositeLit{Type: returnLitStructType, Elts: returnElts}
	returnStmt := &ast.ReturnStmt{Results: []ast.Expr{returnLit}}

	// Build function body: inits... + return
	allStmts := append(initStmts, returnStmt)
	body := &ast.BlockStmt{List: allStmts}

	// Build IIFE: func() struct{...} { ... }()
	funcLit := astFuncLit(
		&ast.FieldList{},
		&ast.FieldList{List: []*ast.Field{{Type: returnStructType}}},
		body,
	)
	iife := &ast.CallExpr{Fun: funcLit}

	// Build var decl with hash comment
	hashComment := astCommentGroup(fmt.Sprintf("// braider:hash:%s", hash))
	varDecl := astVarDecl(hashComment, "dependency", iife)

	// Render
	dependencyVar, err := renderDecl(varDecl)
	if err != nil {
		return nil, fmt.Errorf("failed to format bootstrap code: %w", err)
	}

	return &GeneratedBootstrap{
		DependencyVar: dependencyVar,
		MainReference: "_ = dependency",
		Imports:       imports,
		Hash:          hash,
	}, nil
}

// buildNodeTypeExpr constructs the type expression for a graph node.
func (bg *bootstrapGenerator) buildNodeTypeExpr(
	node *graph.Node,
	currentPackage, currentPkgName string,
	aliasMap map[string]string,
) ast.Expr {
	if node.RegisteredType != nil {
		typeStr := types.TypeString(
			node.RegisteredType, func(p *types.Package) string {
				if p == nil {
					return ""
				}
				if p.Path() == currentPackage {
					return ""
				}
				if alias, ok := aliasMap[p.Path()]; ok && alias != "" {
					return alias
				}
				return p.Name()
			},
		)
		return parseExprString(typeStr)
	}

	// Concrete type (default behavior)
	qualifier := node.PackageAlias
	if qualifier == "" {
		qualifier = node.PackageName
	}

	if node.PackageName == "main" && currentPkgName == "main" {
		return &ast.Ident{Name: node.LocalName}
	} else if node.PackageName != currentPkgName {
		return astSelector(qualifier, node.LocalName)
	}
	return &ast.Ident{Name: node.LocalName}
}

// resolveVarName determines the variable name for a node in bootstrap code.
func (bg *bootstrapGenerator) resolveVarName(
	node *graph.Node, typeName string, fieldNames map[string]string,
) string {
	if node.IsField {
		return fieldNames[typeName]
	}
	varName := node.Name
	if varName == "" {
		varName = DeriveFieldName(typeName)
	}
	return varName
}

// resolveExpressionText computes the final expression text for a Variable node,
// applying package qualification and alias rewriting as needed.
func (bg *bootstrapGenerator) resolveExpressionText(
	node *graph.Node,
	currentPackage, currentPkgName string,
	aliasMap map[string]string,
) string {
	expressionText := node.ExpressionText
	if !node.IsQualified && node.PackagePath != currentPackage {
		qualifier := node.PackageAlias
		if qualifier == "" {
			qualifier = node.PackageName
		}
		expressionText = qualifier + "." + expressionText
	} else if node.IsQualified {
		expressionText = rewriteExpressionAliases(
			expressionText,
			node.ExpressionPkgs,
			node.ExpressionPkgNames,
			aliasMap,
		)
	}
	return expressionText
}

// buildConstructorCallExpr constructs the function call expression for a node's constructor.
func (bg *bootstrapGenerator) buildConstructorCallExpr(
	node *graph.Node,
	g *graph.Graph,
	fieldNames map[string]string,
	currentPkgName string,
) *ast.CallExpr {
	// Build args
	var args []ast.Expr
	for _, depTypeName := range node.Dependencies {
		depNode := g.Nodes[depTypeName]
		if depNode == nil {
			continue
		}
		depVarName := bg.resolveDepVarName(depNode, depTypeName, fieldNames)
		args = append(args, &ast.Ident{Name: depVarName})
	}

	// Determine function reference with package qualifier
	ctorPkgName := node.ConstructorPkgName
	if ctorPkgName == "" {
		ctorPkgName = node.PackageName
	}
	constructorQualifier := node.ConstructorPkgAlias
	if constructorQualifier == "" {
		constructorQualifier = ctorPkgName
	}

	var funExpr ast.Expr
	if ctorPkgName == "main" && currentPkgName == "main" {
		funExpr = &ast.Ident{Name: node.ConstructorName}
	} else if ctorPkgName != currentPkgName {
		funExpr = astSelector(constructorQualifier, node.ConstructorName)
	} else {
		funExpr = &ast.Ident{Name: node.ConstructorName}
	}

	return &ast.CallExpr{Fun: funExpr, Args: args}
}

// resolveDepVarName resolves the variable name for a dependency node.
func (bg *bootstrapGenerator) resolveDepVarName(
	depNode *graph.Node, depTypeName string, fieldNames map[string]string,
) string {
	if depNode.IsField {
		return fieldNames[depTypeName]
	}
	depVarName := depNode.Name
	if depVarName == "" {
		depVarName = DeriveFieldName(depTypeName)
	}
	return depVarName
}

// DetectExistingBootstrap finds an existing bootstrap variable declaration.
func (bg *bootstrapGenerator) DetectExistingBootstrap(pass *analysis.Pass) *ast.GenDecl {
	for _, file := range pass.Files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.VAR {
				continue
			}

			for _, spec := range genDecl.Specs {
				valueSpec, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}

				for _, name := range valueSpec.Names {
					if name.Name == "dependency" {
						return genDecl
					}
				}
			}
		}
	}
	return nil
}

// CheckBootstrapCurrent checks if the existing bootstrap code is up-to-date.
func (bg *bootstrapGenerator) CheckBootstrapCurrent(
	pass *analysis.Pass,
	existing *ast.GenDecl,
	g *graph.Graph,
) bool {
	if existing == nil || g == nil {
		return false
	}

	// Extract hash from comment
	existingHash := extractHashFromComments(existing.Doc)
	if existingHash == "" {
		return false
	}

	// Compute current hash
	currentHash := ComputeGraphHash(g)

	return existingHash == currentHash
}

// GenerateContainerBootstrap generates container-aware bootstrap code.
// Instead of returning an anonymous struct, it returns the user-defined container struct
// with fields mapped from resolved dependencies.
func (bg *bootstrapGenerator) GenerateContainerBootstrap(
	pass *analysis.Pass,
	g *graph.Graph,
	sortedTypes []string,
	containerDef *detect.ContainerDefinition,
	resolvedFields []detect.ResolvedContainerField,
) (*GeneratedBootstrap, error) {
	if g == nil {
		return nil, fmt.Errorf("nil dependency graph")
	}
	if containerDef == nil {
		return nil, fmt.Errorf("nil container definition")
	}

	// Compute container hash for idempotency
	hash := ComputeContainerHash(g, containerDef)

	// Detect existing aliases from the target file
	var targetFile *ast.File
	existingBootstrap := bg.DetectExistingBootstrap(pass)
	if existingBootstrap != nil {
		for _, file := range pass.Files {
			for _, decl := range file.Decls {
				if decl == existingBootstrap {
					targetFile = file
					break
				}
			}
			if targetFile != nil {
				break
			}
		}
	}
	if targetFile == nil && len(pass.Files) > 0 {
		targetFile = pass.Files[0]
	}
	existingAliases := detectExistingAliases(targetFile)

	// Collect imports (including container type imports)
	currentPackage := pass.Pkg.Path()
	currentPkgName := pass.Pkg.Name()
	imports, aliasMap := CollectContainerImports(g, containerDef, currentPackage, currentPkgName, existingAliases)

	// Build a map from node key to variable name (all nodes become local vars in container mode)
	varNames := make(map[string]string) // nodeKey -> varName
	for _, typeName := range sortedTypes {
		node := g.Nodes[typeName]
		if node == nil {
			continue
		}
		varName := node.Name
		if varName == "" {
			varName = DeriveFieldName(typeName)
		}
		varNames[typeName] = varName
	}

	// Build a set of node keys that are depended upon by other nodes or referenced by container fields.
	dependedUpon := make(map[string]struct{})
	for _, node := range g.Nodes {
		for _, dep := range node.Dependencies {
			dependedUpon[dep] = struct{}{}
		}
	}
	for _, rf := range resolvedFields {
		dependedUpon[rf.NodeKey] = struct{}{}
	}

	// Generate initialization statements as AST
	var initStmts []ast.Stmt
	for _, typeName := range sortedTypes {
		node := g.Nodes[typeName]
		if node == nil {
			continue
		}

		varName := varNames[typeName]

		// Variable node: emit expression assignment
		if node.ExpressionText != "" {
			expressionText := bg.resolveExpressionText(node, currentPackage, currentPkgName, aliasMap)
			exprAST := parseExprString(expressionText)
			if _, ok := dependedUpon[typeName]; ok {
				initStmts = append(initStmts, astShortVar(varName, exprAST))
			} else {
				initStmts = append(initStmts, astBlankAssign(exprAST))
			}
			continue
		}

		// Provider/Injector node: constructor call
		if len(node.ConstructorName) == 0 {
			return nil, fmt.Errorf("injectable struct %s requires a constructor", typeName)
		}

		callExpr := bg.buildContainerConstructorCallExpr(node, g, varNames, currentPkgName)
		initStmts = append(initStmts, astShortVar(varName, callExpr))
	}

	// Build the IIFE return type as an ast.Expr
	var returnTypeExpr ast.Expr
	if containerDef.IsNamed {
		if containerDef.PackagePath == currentPackage || containerDef.PackageName == currentPkgName {
			returnTypeExpr = &ast.Ident{Name: containerDef.LocalName}
		} else {
			containerQualifier := containerDef.PackageName
			if alias, ok := aliasMap[containerDef.PackagePath]; ok && alias != "" {
				containerQualifier = alias
			}
			returnTypeExpr = astSelector(containerQualifier, containerDef.LocalName)
		}
	} else {
		// Anonymous struct type
		var anonFields []*ast.Field
		for _, field := range containerDef.Fields {
			fieldTypeStr := types.TypeString(field.Type, func(p *types.Package) string {
				if p == nil {
					return ""
				}
				if p.Path() == currentPackage {
					return ""
				}
				if alias, ok := aliasMap[p.Path()]; ok && alias != "" {
					return alias
				}
				return p.Name()
			})
			anonFields = append(anonFields, &ast.Field{Names: []*ast.Ident{{Name: field.Name}}, Type: parseExprString(fieldTypeStr)})
		}
		returnTypeExpr = astStructType(anonFields...)
	}

	// Build return composite literal with container field assignments
	var returnElts []ast.Expr
	for _, rf := range resolvedFields {
		returnElts = append(returnElts, &ast.KeyValueExpr{Key: &ast.Ident{Name: rf.FieldName}, Value: &ast.Ident{Name: rf.VarName}})
	}

	// Build duplicate return type for the composite literal
	var returnLitType ast.Expr
	if containerDef.IsNamed {
		if containerDef.PackagePath == currentPackage || containerDef.PackageName == currentPkgName {
			returnLitType = &ast.Ident{Name: containerDef.LocalName}
		} else {
			containerQualifier := containerDef.PackageName
			if alias, ok := aliasMap[containerDef.PackagePath]; ok && alias != "" {
				containerQualifier = alias
			}
			returnLitType = astSelector(containerQualifier, containerDef.LocalName)
		}
	} else {
		var anonFields []*ast.Field
		for _, field := range containerDef.Fields {
			fieldTypeStr := types.TypeString(field.Type, func(p *types.Package) string {
				if p == nil {
					return ""
				}
				if p.Path() == currentPackage {
					return ""
				}
				if alias, ok := aliasMap[p.Path()]; ok && alias != "" {
					return alias
				}
				return p.Name()
			})
			anonFields = append(anonFields, &ast.Field{Names: []*ast.Ident{{Name: field.Name}}, Type: parseExprString(fieldTypeStr)})
		}
		returnLitType = astStructType(anonFields...)
	}

	returnLit := &ast.CompositeLit{Type: returnLitType, Elts: returnElts}
	returnStmt := &ast.ReturnStmt{Results: []ast.Expr{returnLit}}

	// Build function body
	allStmts := append(initStmts, returnStmt)
	body := &ast.BlockStmt{List: allStmts}

	// Build IIFE
	funcLit := astFuncLit(
		&ast.FieldList{},
		&ast.FieldList{List: []*ast.Field{{Type: returnTypeExpr}}},
		body,
	)
	iife := &ast.CallExpr{Fun: funcLit}

	// Build var decl with hash comment
	hashComment := astCommentGroup(fmt.Sprintf("// braider:hash:%s", hash))
	varDecl := astVarDecl(hashComment, "dependency", iife)

	// Render
	dependencyVar, err := renderDecl(varDecl)
	if err != nil {
		return nil, fmt.Errorf("failed to format container bootstrap code: %w", err)
	}

	return &GeneratedBootstrap{
		DependencyVar: dependencyVar,
		MainReference: "_ = dependency",
		Imports:       imports,
		Hash:          hash,
	}, nil
}

// buildContainerConstructorCallExpr builds a constructor call for container bootstrap.
// Uses varNames map (all nodes are local vars in container mode).
func (bg *bootstrapGenerator) buildContainerConstructorCallExpr(
	node *graph.Node,
	g *graph.Graph,
	varNames map[string]string,
	currentPkgName string,
) *ast.CallExpr {
	var args []ast.Expr
	for _, depTypeName := range node.Dependencies {
		depVarName := varNames[depTypeName]
		if depVarName == "" {
			depNode := g.Nodes[depTypeName]
			if depNode != nil {
				depVarName = depNode.Name
				if depVarName == "" {
					depVarName = DeriveFieldName(depTypeName)
				}
			}
		}
		args = append(args, &ast.Ident{Name: depVarName})
	}

	qualifier := node.PackageAlias
	if qualifier == "" {
		qualifier = node.PackageName
	}

	var funExpr ast.Expr
	if node.PackageName == "main" && currentPkgName == "main" {
		funExpr = &ast.Ident{Name: node.ConstructorName}
	} else if node.PackageName != currentPkgName {
		funExpr = astSelector(qualifier, node.ConstructorName)
	} else {
		funExpr = &ast.Ident{Name: node.ConstructorName}
	}

	return &ast.CallExpr{Fun: funExpr, Args: args}
}

// CheckContainerBootstrapCurrent checks if the existing container bootstrap code is up-to-date.
func (bg *bootstrapGenerator) CheckContainerBootstrapCurrent(
	pass *analysis.Pass,
	existing *ast.GenDecl,
	g *graph.Graph,
	containerDef *detect.ContainerDefinition,
) bool {
	if existing == nil || g == nil {
		return false
	}

	existingHash := extractHashFromComments(existing.Doc)
	if existingHash == "" {
		return false
	}

	currentHash := ComputeContainerHash(g, containerDef)

	return existingHash == currentHash
}

// rewriteExpressionAliases replaces declared package name prefixes in expressionText
// with their collision aliases from aliasMap. This is needed when a package name collision
// causes an alias to be generated (e.g., "os" -> "os2"), but ExpressionText still uses
// the declared name (e.g., "os.Stdout" must become "os2.Stdout").
func rewriteExpressionAliases(
	expressionText string,
	exprPkgs []string,
	exprPkgNames []string,
	aliasMap map[string]string,
) string {
	for i, pkgPath := range exprPkgs {
		if i >= len(exprPkgNames) {
			break
		}
		alias, exists := aliasMap[pkgPath]
		if !exists || alias == "" {
			continue
		}
		declaredName := exprPkgNames[i]
		prefix := declaredName + "."
		if strings.HasPrefix(expressionText, prefix) {
			expressionText = alias + "." + expressionText[len(prefix):]
		}
	}
	return expressionText
}

// extractHashFromComments extracts the hash marker from comment group.
// Expected format: "// braider:hash:abc12345" (with flexible whitespace)
func extractHashFromComments(doc *ast.CommentGroup) string {
	if doc == nil {
		return ""
	}

	// Use cached regex for flexible matching
	for _, comment := range doc.List {
		if matches := hashCommentRe.FindStringSubmatch(comment.Text); matches != nil {
			return matches[1]
		}
	}
	return ""
}
