// Package generate provides code generation capabilities for braider analyzer.
package generate

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/printer"
	"go/token"
	"go/types"
	"strings"

	"github.com/miyamo2/braider/internal/detect"
	"github.com/miyamo2/braider/internal/registry"
	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
)

// GeneratedConstructor contains the generated constructor code.
type GeneratedConstructor struct {
	FuncName   string // Function name (New<UpperCamelCaseStructName>)
	StructName string // Original struct name
	Code       string // Formatted constructor source code
}

// ConstructorGenerator generates constructor function code.
type ConstructorGenerator interface {
	// GenerateConstructor creates constructor code for a struct.
	GenerateConstructor(candidate detect.ConstructorCandidate, fields []detect.FieldInfo) (*GeneratedConstructor, error)

	// GenerateConstructorWithOptions creates constructor code with option-aware return type.
	// Returns nil if WithoutConstructor option is set.
	// Task 5.1: Implement option-aware return type selection.
	GenerateConstructorWithOptions(
		candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
	) (*GeneratedConstructor, error)

	// GenerateConstructorWithNamedDeps creates constructor code with named dependency parameters.
	// dependencyNames maps field names to custom parameter names for named dependencies.
	// Task 5.2: Implement named dependency parameter naming.
	GenerateConstructorWithNamedDeps(
		candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
		dependencyNames map[string]string,
	) (*GeneratedConstructor, error)
}

// constructorGenerator is the default implementation of ConstructorGenerator.
type constructorGenerator struct {
	annotation.Injectable[inject.Typed[ConstructorGenerator]]
}

// GenerateConstructor creates constructor code for a struct.
func (g *constructorGenerator) GenerateConstructor(
	candidate detect.ConstructorCandidate, fields []detect.FieldInfo,
) (*GeneratedConstructor, error) {
	structName := candidate.TypeSpec.Name.Name
	funcName := "New" + ToUpperCamelCase(structName)

	// Build parameter list
	params := g.buildParams(fields)

	// Build field assignments
	assignments := g.buildAssignments(fields)

	// Generate the constructor code
	var buf bytes.Buffer

	// Write GoDoc
	fmt.Fprintf(&buf, "// %s is a constructor for %s.\n", funcName, structName)
	fmt.Fprintf(&buf, "//\n")
	fmt.Fprintf(&buf, "// Generated by braider. DO NOT EDIT.\n")

	// Write function signature
	if len(params) > 0 {
		fmt.Fprintf(&buf, "func %s(%s) *%s {\n", funcName, params, structName)
	} else {
		fmt.Fprintf(&buf, "func %s() *%s {\n", funcName, structName)
	}

	// Write return statement
	if len(fields) > 0 {
		fmt.Fprintf(&buf, "\treturn &%s{\n", structName)
		for _, assignment := range assignments {
			fmt.Fprintf(&buf, "\t\t%s,\n", assignment)
		}
		fmt.Fprintf(&buf, "\t}\n")
	} else {
		fmt.Fprintf(&buf, "\treturn &%s{}\n", structName)
	}

	fmt.Fprintf(&buf, "}\n")

	// Format the code
	formatted, err := formatConstructor(buf.Bytes())
	if err != nil {
		// Return unformatted code with error
		return &GeneratedConstructor{
			FuncName:   funcName,
			StructName: structName,
			Code:       buf.String(),
		}, fmt.Errorf("failed to format constructor: %w", err)
	}

	return &GeneratedConstructor{
		FuncName:   funcName,
		StructName: structName,
		Code:       string(formatted),
	}, nil
}

// buildParams builds the parameter list string for the constructor.
func (g *constructorGenerator) buildParams(fields []detect.FieldInfo) string {
	if len(fields) == 0 {
		return ""
	}

	var params []string
	for _, field := range fields {
		paramName := DeriveParamName(field.Name)
		typeStr := typeExprToString(field.TypeExpr)
		params = append(params, fmt.Sprintf("%s %s", paramName, typeStr))
	}

	return strings.Join(params, ", ")
}

// buildAssignments builds the field assignment strings for the constructor body.
func (g *constructorGenerator) buildAssignments(fields []detect.FieldInfo) []string {
	if len(fields) == 0 {
		return nil
	}

	// Find max field name length for alignment
	maxLen := 0
	for _, field := range fields {
		if len(field.Name) > maxLen {
			maxLen = len(field.Name)
		}
	}

	var assignments []string
	for _, field := range fields {
		paramName := DeriveParamName(field.Name)
		// Pad field name for alignment
		padding := strings.Repeat(" ", maxLen-len(field.Name))
		assignments = append(assignments, fmt.Sprintf("%s:%s %s", field.Name, padding, paramName))
	}

	return assignments
}

// typeExprToString converts an AST type expression to its string representation.
func typeExprToString(expr ast.Expr) string {
	if expr == nil {
		return ""
	}

	var buf bytes.Buffer
	fset := token.NewFileSet()
	if err := printer.Fprint(&buf, fset, expr); err != nil {
		// Fallback: try to handle manually
		return typeExprToStringManual(expr)
	}
	return buf.String()
}

// typeExprToStringManual manually converts AST expression to string (fallback).
func typeExprToStringManual(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		return "*" + typeExprToStringManual(e.X)
	case *ast.SelectorExpr:
		return typeExprToStringManual(e.X) + "." + e.Sel.Name
	case *ast.ArrayType:
		if e.Len == nil {
			return "[]" + typeExprToStringManual(e.Elt)
		}
		return "[...]" + typeExprToStringManual(e.Elt)
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", typeExprToStringManual(e.Key), typeExprToStringManual(e.Value))
	case *ast.ChanType:
		switch e.Dir {
		case ast.SEND:
			return "chan<- " + typeExprToStringManual(e.Value)
		case ast.RECV:
			return "<-chan " + typeExprToStringManual(e.Value)
		default:
			return "chan " + typeExprToStringManual(e.Value)
		}
	default:
		return fmt.Sprintf("%T", expr)
	}
}

// DeriveParamName converts a field name to a valid parameter name.
// Rules:
// 1. Convert to lowerCamelCase (handle all-caps like "DB" -> "db")
// 2. If result is a Go keyword, append underscore
// 3. If result conflicts with builtin, use field name with "Param" suffix
func DeriveParamName(fieldName string) string {
	if fieldName == "" {
		return "param"
	}

	// Convert to lowercase - handle all-caps names like "DB" -> "db"
	paramName := ToLowerCamelCase(fieldName)

	// Check for keyword conflicts
	if IsGoKeyword(paramName) {
		return paramName + "_"
	}

	// Check for builtin conflicts
	if IsGoBuiltin(paramName) {
		return paramName + "Param"
	}

	return paramName
}

// GenerateConstructorWithOptions creates constructor code with option-aware return type.
// Returns nil if WithoutConstructor option is set (Task 5.1).
func (g *constructorGenerator) GenerateConstructorWithOptions(
	candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
) (*GeneratedConstructor, error) {
	// Task 5.1: Check WithoutConstructor option - skip generation if set
	if info != nil && info.OptionMetadata.WithoutConstructor {
		return nil, nil
	}

	structName := candidate.TypeSpec.Name.Name
	funcName := "New" + ToUpperCamelCase(structName)

	// Build parameter list
	params := g.buildParams(fields)

	// Build field assignments
	assignments := g.buildAssignments(fields)

	// Task 5.1: Determine return type based on options
	returnType := g.determineReturnType(structName, info)

	// Generate the constructor code
	var buf bytes.Buffer

	// Write GoDoc
	fmt.Fprintf(&buf, "// %s is a constructor for %s.\n", funcName, structName)
	fmt.Fprintf(&buf, "//\n")
	fmt.Fprintf(&buf, "// Generated by braider. DO NOT EDIT.\n")

	// Write function signature with option-aware return type
	if len(params) > 0 {
		fmt.Fprintf(&buf, "func %s(%s) %s {\n", funcName, params, returnType)
	} else {
		fmt.Fprintf(&buf, "func %s() %s {\n", funcName, returnType)
	}

	// Write return statement
	if len(fields) > 0 {
		fmt.Fprintf(&buf, "\treturn &%s{\n", structName)
		for _, assignment := range assignments {
			fmt.Fprintf(&buf, "\t\t%s,\n", assignment)
		}
		fmt.Fprintf(&buf, "\t}\n")
	} else {
		fmt.Fprintf(&buf, "\treturn &%s{}\n", structName)
	}

	fmt.Fprintf(&buf, "}\n")

	// Format the code
	formatted, err := formatConstructor(buf.Bytes())
	if err != nil {
		// Return unformatted code with error
		return &GeneratedConstructor{
			FuncName:   funcName,
			StructName: structName,
			Code:       buf.String(),
		}, fmt.Errorf("failed to format constructor: %w", err)
	}

	return &GeneratedConstructor{
		FuncName:   funcName,
		StructName: structName,
		Code:       string(formatted),
	}, nil
}

// determineReturnType determines constructor return type based on option metadata.
// Task 5.1: Returns interface type for Typed[I] option, pointer to struct otherwise.
func (g *constructorGenerator) determineReturnType(structName string, info *registry.InjectorInfo) string {
	if info == nil || info.OptionMetadata.TypedInterface == nil {
		// Default: return pointer to struct
		return "*" + structName
	}

	// Typed[I] option: return interface type
	return types.TypeString(
		info.OptionMetadata.TypedInterface, func(p *types.Package) string {
			// Use unqualified type name (same package context)
			return ""
		},
	)
}

// GenerateConstructorWithNamedDeps creates constructor code with named dependency parameters.
// Task 5.2: Supports custom parameter names for named dependencies.
func (g *constructorGenerator) GenerateConstructorWithNamedDeps(
	candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
	dependencyNames map[string]string,
) (*GeneratedConstructor, error) {
	// Task 5.1: Check WithoutConstructor option first
	if info != nil && info.OptionMetadata.WithoutConstructor {
		return nil, nil
	}

	structName := candidate.TypeSpec.Name.Name
	funcName := "New" + ToUpperCamelCase(structName)

	// Task 5.2: Build parameter list with named dependencies
	params := g.buildParamsWithNames(fields, dependencyNames)

	// Task 5.2: Build field assignments with named dependencies
	assignments := g.buildAssignmentsWithNames(fields, dependencyNames)

	// Task 5.1: Determine return type based on options
	returnType := g.determineReturnType(structName, info)

	// Generate the constructor code
	var buf bytes.Buffer

	// Write GoDoc
	fmt.Fprintf(&buf, "// %s is a constructor for %s.\n", funcName, structName)
	fmt.Fprintf(&buf, "//\n")
	fmt.Fprintf(&buf, "// Generated by braider. DO NOT EDIT.\n")

	// Write function signature
	if len(params) > 0 {
		fmt.Fprintf(&buf, "func %s(%s) %s {\n", funcName, params, returnType)
	} else {
		fmt.Fprintf(&buf, "func %s() %s {\n", funcName, returnType)
	}

	// Write return statement
	if len(fields) > 0 {
		fmt.Fprintf(&buf, "\treturn &%s{\n", structName)
		for _, assignment := range assignments {
			fmt.Fprintf(&buf, "\t\t%s,\n", assignment)
		}
		fmt.Fprintf(&buf, "\t}\n")
	} else {
		fmt.Fprintf(&buf, "\treturn &%s{}\n", structName)
	}

	fmt.Fprintf(&buf, "}\n")

	// Format the code
	formatted, err := formatConstructor(buf.Bytes())
	if err != nil {
		// Return unformatted code with error
		return &GeneratedConstructor{
			FuncName:   funcName,
			StructName: structName,
			Code:       buf.String(),
		}, fmt.Errorf("failed to format constructor: %w", err)
	}

	return &GeneratedConstructor{
		FuncName:   funcName,
		StructName: structName,
		Code:       string(formatted),
	}, nil
}

// buildParamsWithNames builds parameter list with custom names for named dependencies.
// Task 5.2: Uses dependencyNames map to override default parameter names.
func (g *constructorGenerator) buildParamsWithNames(
	fields []detect.FieldInfo, dependencyNames map[string]string,
) string {
	if len(fields) == 0 {
		return ""
	}

	var params []string
	for _, field := range fields {
		// Task 5.2: Check if this field has a custom parameter name
		paramName, hasCustomName := dependencyNames[field.Name]
		if !hasCustomName {
			// Use default parameter name
			paramName = DeriveParamName(field.Name)
		}

		typeStr := typeExprToString(field.TypeExpr)
		params = append(params, fmt.Sprintf("%s %s", paramName, typeStr))
	}

	return strings.Join(params, ", ")
}

// buildAssignmentsWithNames builds field assignments with custom parameter names.
// Task 5.2: Uses dependencyNames map for parameter references in assignments.
func (g *constructorGenerator) buildAssignmentsWithNames(
	fields []detect.FieldInfo, dependencyNames map[string]string,
) []string {
	if len(fields) == 0 {
		return nil
	}

	// Find max field name length for alignment
	maxLen := 0
	for _, field := range fields {
		if len(field.Name) > maxLen {
			maxLen = len(field.Name)
		}
	}

	var assignments []string
	for _, field := range fields {
		// Task 5.2: Use custom parameter name if available
		paramName, hasCustomName := dependencyNames[field.Name]
		if !hasCustomName {
			paramName = DeriveParamName(field.Name)
		}

		// Pad field name for alignment
		padding := strings.Repeat(" ", maxLen-len(field.Name))
		assignments = append(assignments, fmt.Sprintf("%s:%s %s", field.Name, padding, paramName))
	}

	return assignments
}

// formatConstructor formats a constructor code fragment as Go source.
// It wraps the fragment in a package declaration so that format.Source
// treats it as a complete file, preserving blank comment lines.
func formatConstructor(src []byte) ([]byte, error) {
	const prefix = "package _\n\n"
	wrapped := make([]byte, 0, len(prefix)+len(src))
	wrapped = append(wrapped, prefix...)
	wrapped = append(wrapped, src...)

	formatted, err := format.Source(wrapped)
	if err != nil {
		return nil, err
	}

	// Strip the package declaration prefix
	s := string(formatted)
	if idx := strings.Index(s, "\n\n"); idx >= 0 {
		return []byte(s[idx+2:]), nil
	}
	return formatted, nil
}
