// Package generate provides code generation capabilities for braider analyzer.
package generate

import (
	"fmt"
	"go/ast"
	"go/token"
	"go/types"

	"github.com/miyamo2/braider/internal/detect"
	"github.com/miyamo2/braider/internal/registry"
	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
)

// GeneratedConstructor contains the generated constructor code.
type GeneratedConstructor struct {
	FuncName   string // Function name (New<UpperCamelCaseStructName>)
	StructName string // Original struct name
	Code       string // Formatted constructor source code
}

// ConstructorGenerator generates constructor function code.
type ConstructorGenerator interface {
	// GenerateConstructor creates constructor code for a struct.
	GenerateConstructor(candidate detect.ConstructorCandidate, fields []detect.FieldInfo) (*GeneratedConstructor, error)

	// GenerateConstructorWithOptions creates constructor code with option-aware return type.
	// Returns nil if WithoutConstructor option is set.
	GenerateConstructorWithOptions(
		candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
	) (*GeneratedConstructor, error)

	// GenerateConstructorWithNamedDeps creates constructor code with named dependency parameters.
	// dependencyNames maps field names to custom parameter names for named dependencies.
	GenerateConstructorWithNamedDeps(
		candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
		dependencyNames map[string]string,
	) (*GeneratedConstructor, error)
}

// constructorGenerator is the default implementation of ConstructorGenerator.
type constructorGenerator struct {
	annotation.Injectable[inject.Typed[ConstructorGenerator]]
}

// NewConstructorGenerator is a constructor for constructorGenerator.
//
// Generated by braider. DO NOT EDIT.
func NewConstructorGenerator() *constructorGenerator {
	return &constructorGenerator{}
}

// GenerateConstructor creates constructor code for a struct.
func (g *constructorGenerator) GenerateConstructor(
	candidate detect.ConstructorCandidate, fields []detect.FieldInfo,
) (*GeneratedConstructor, error) {
	structName := candidate.TypeSpec.Name.Name
	funcName := "New" + ToUpperCamelCase(structName)

	returnTypeExpr := &ast.StarExpr{X: &ast.Ident{Name: structName}}
	funcDecl, err := g.buildConstructorAST(funcName, structName, fields, returnTypeExpr, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to build constructor AST for %s: %w", structName, err)
	}

	code, err := renderDecl(funcDecl)
	if err != nil {
		return &GeneratedConstructor{
			FuncName:   funcName,
			StructName: structName,
		}, fmt.Errorf("failed to format constructor: %w", err)
	}

	return &GeneratedConstructor{
		FuncName:   funcName,
		StructName: structName,
		Code:       code,
	}, nil
}

// GenerateConstructorWithOptions creates constructor code with option-aware return type.
// Returns nil if WithoutConstructor option is set.
func (g *constructorGenerator) GenerateConstructorWithOptions(
	candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
) (*GeneratedConstructor, error) {
	// Check WithoutConstructor option - skip generation if set
	if info != nil && info.OptionMetadata.WithoutConstructor {
		return nil, nil
	}

	structName := candidate.TypeSpec.Name.Name
	funcName := "New" + ToUpperCamelCase(structName)

	// Determine return type based on options
	returnTypeExpr, err := g.determineReturnTypeExpr(structName, info)
	if err != nil {
		return nil, fmt.Errorf("failed to determine return type for %s: %w", structName, err)
	}
	funcDecl, err := g.buildConstructorAST(funcName, structName, fields, returnTypeExpr, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to build constructor AST for %s: %w", structName, err)
	}

	code, err := renderDecl(funcDecl)
	if err != nil {
		return &GeneratedConstructor{
			FuncName:   funcName,
			StructName: structName,
		}, fmt.Errorf("failed to format constructor: %w", err)
	}

	return &GeneratedConstructor{
		FuncName:   funcName,
		StructName: structName,
		Code:       code,
	}, nil
}

// GenerateConstructorWithNamedDeps creates constructor code with named dependency parameters.
// Supports custom parameter names for named dependencies.
func (g *constructorGenerator) GenerateConstructorWithNamedDeps(
	candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
	dependencyNames map[string]string,
) (*GeneratedConstructor, error) {
	// Check WithoutConstructor option first
	if info != nil && info.OptionMetadata.WithoutConstructor {
		return nil, nil
	}

	structName := candidate.TypeSpec.Name.Name
	funcName := "New" + ToUpperCamelCase(structName)

	// Determine return type based on options
	returnTypeExpr, err := g.determineReturnTypeExpr(structName, info)
	if err != nil {
		return nil, fmt.Errorf("failed to determine return type for %s: %w", structName, err)
	}
	funcDecl, err := g.buildConstructorAST(funcName, structName, fields, returnTypeExpr, dependencyNames)
	if err != nil {
		return nil, fmt.Errorf("failed to build constructor AST for %s: %w", structName, err)
	}

	code, err := renderDecl(funcDecl)
	if err != nil {
		return &GeneratedConstructor{
			FuncName:   funcName,
			StructName: structName,
		}, fmt.Errorf("failed to format constructor: %w", err)
	}

	return &GeneratedConstructor{
		FuncName:   funcName,
		StructName: structName,
		Code:       code,
	}, nil
}

// buildConstructorAST constructs the complete *ast.FuncDecl for a constructor.
// dependencyNames maps field names to custom parameter names (may be nil).
func (g *constructorGenerator) buildConstructorAST(
	funcName, structName string,
	fields []detect.FieldInfo,
	returnTypeExpr ast.Expr,
	dependencyNames map[string]string,
) (*ast.FuncDecl, error) {
	// Build doc comment
	doc := astCommentGroup(
		fmt.Sprintf("// %s is a constructor for %s.", funcName, structName),
		"//",
		"// Generated by braider. DO NOT EDIT.",
	)

	// Build parameter list
	var params []*ast.Field
	for _, field := range fields {
		paramName := g.resolveParamName(field.Name, dependencyNames)
		typ := field.TypeExpr
		if typ == nil {
			return nil, fmt.Errorf("field %q in struct %s has nil type expression", field.Name, structName)
		}
		params = append(params, &ast.Field{Names: []*ast.Ident{{Name: paramName}}, Type: typ})
	}

	// Build body: return &StructName{field: param, ...}
	var body *ast.BlockStmt
	if len(fields) > 0 {
		var elts []ast.Expr
		for _, field := range fields {
			paramName := g.resolveParamName(field.Name, dependencyNames)
			elts = append(elts, &ast.KeyValueExpr{Key: &ast.Ident{Name: field.Name}, Value: &ast.Ident{Name: paramName}})
		}
		body = &ast.BlockStmt{List: []ast.Stmt{
			&ast.ReturnStmt{Results: []ast.Expr{
				&ast.UnaryExpr{Op: token.AND, X: &ast.CompositeLit{Type: &ast.Ident{Name: structName}, Elts: elts}},
			}},
		}}
	} else {
		body = &ast.BlockStmt{List: []ast.Stmt{
			&ast.ReturnStmt{Results: []ast.Expr{
				&ast.UnaryExpr{Op: token.AND, X: &ast.CompositeLit{Type: &ast.Ident{Name: structName}}},
			}},
		}}
	}

	paramList := &ast.FieldList{List: params}
	resultList := &ast.FieldList{List: []*ast.Field{{Type: returnTypeExpr}}}

	return &ast.FuncDecl{
		Doc:  doc,
		Name: &ast.Ident{Name: funcName},
		Type: &ast.FuncType{
			Params:  paramList,
			Results: resultList,
		},
		Body: body,
	}, nil
}

// resolveParamName returns the parameter name for a field.
// If dependencyNames has a custom name for the field, use it; otherwise derive from field name.
func (g *constructorGenerator) resolveParamName(fieldName string, dependencyNames map[string]string) string {
	if dependencyNames != nil {
		if customName, ok := dependencyNames[fieldName]; ok {
			return customName
		}
	}
	return DeriveParamName(fieldName)
}

// determineReturnTypeExpr determines constructor return type as an ast.Expr based on option metadata.
// Returns interface type for Typed[I] option, pointer to struct otherwise.
func (g *constructorGenerator) determineReturnTypeExpr(structName string, info *registry.InjectorInfo) (ast.Expr, error) {
	if info == nil || info.OptionMetadata.TypedInterface == nil {
		// Default: return pointer to struct
		return &ast.StarExpr{X: &ast.Ident{Name: structName}}, nil
	}

	// Typed[I] option: return interface type
	typeStr := types.TypeString(
		info.OptionMetadata.TypedInterface, func(p *types.Package) string {
			// Use unqualified type name (same package context)
			return ""
		},
	)
	return parseExprString(typeStr)
}

// DeriveParamName converts a field name to a valid parameter name.
// Rules:
// 1. Convert to lowerCamelCase (handle all-caps like "DB" -> "db")
// 2. If result is a Go keyword, append underscore
// 3. If result conflicts with builtin, use field name with "Param" suffix
func DeriveParamName(fieldName string) string {
	if fieldName == "" {
		return "param"
	}

	// Convert to lowercase - handle all-caps names like "DB" -> "db"
	paramName := ToLowerCamelCase(fieldName)

	// Check for keyword conflicts
	if IsGoKeyword(paramName) {
		return paramName + "_"
	}

	// Check for builtin conflicts
	if IsGoBuiltin(paramName) {
		return paramName + "Param"
	}

	return paramName
}
