// Package generate provides code generation capabilities for braider analyzer.
package generate

import (
	"fmt"
	"go/ast"
	"go/types"

	"github.com/miyamo2/braider/internal/detect"
	"github.com/miyamo2/braider/internal/registry"
	"github.com/miyamo2/braider/pkg/annotation"
	"github.com/miyamo2/braider/pkg/annotation/inject"
)

// GeneratedConstructor contains the generated constructor code.
type GeneratedConstructor struct {
	FuncName   string // Function name (New<UpperCamelCaseStructName>)
	StructName string // Original struct name
	Code       string // Formatted constructor source code
}

// ConstructorGenerator generates constructor function code.
type ConstructorGenerator interface {
	// GenerateConstructor creates constructor code for a struct.
	GenerateConstructor(candidate detect.ConstructorCandidate, fields []detect.FieldInfo) (*GeneratedConstructor, error)

	// GenerateConstructorWithOptions creates constructor code with option-aware return type.
	// Returns nil if WithoutConstructor option is set.
	// Task 5.1: Implement option-aware return type selection.
	GenerateConstructorWithOptions(
		candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
	) (*GeneratedConstructor, error)

	// GenerateConstructorWithNamedDeps creates constructor code with named dependency parameters.
	// dependencyNames maps field names to custom parameter names for named dependencies.
	// Task 5.2: Implement named dependency parameter naming.
	GenerateConstructorWithNamedDeps(
		candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
		dependencyNames map[string]string,
	) (*GeneratedConstructor, error)
}

// constructorGenerator is the default implementation of ConstructorGenerator.
type constructorGenerator struct {
	annotation.Injectable[inject.Typed[ConstructorGenerator]]
}

// NewConstructorGenerator is a constructor for constructorGenerator.
//
// Generated by braider. DO NOT EDIT.
func NewConstructorGenerator() *constructorGenerator {
	return &constructorGenerator{}
}

// GenerateConstructor creates constructor code for a struct.
func (g *constructorGenerator) GenerateConstructor(
	candidate detect.ConstructorCandidate, fields []detect.FieldInfo,
) (*GeneratedConstructor, error) {
	structName := candidate.TypeSpec.Name.Name
	funcName := "New" + ToUpperCamelCase(structName)

	returnTypeExpr := astStar(astIdent(structName))
	funcDecl := g.buildConstructorAST(funcName, structName, fields, returnTypeExpr, nil)

	code, err := renderDecl(funcDecl)
	if err != nil {
		return &GeneratedConstructor{
			FuncName:   funcName,
			StructName: structName,
		}, fmt.Errorf("failed to format constructor: %w", err)
	}

	return &GeneratedConstructor{
		FuncName:   funcName,
		StructName: structName,
		Code:       code,
	}, nil
}

// GenerateConstructorWithOptions creates constructor code with option-aware return type.
// Returns nil if WithoutConstructor option is set (Task 5.1).
func (g *constructorGenerator) GenerateConstructorWithOptions(
	candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
) (*GeneratedConstructor, error) {
	// Task 5.1: Check WithoutConstructor option - skip generation if set
	if info != nil && info.OptionMetadata.WithoutConstructor {
		return nil, nil
	}

	structName := candidate.TypeSpec.Name.Name
	funcName := "New" + ToUpperCamelCase(structName)

	// Task 5.1: Determine return type based on options
	returnTypeExpr := g.determineReturnTypeExpr(structName, info)
	funcDecl := g.buildConstructorAST(funcName, structName, fields, returnTypeExpr, nil)

	code, err := renderDecl(funcDecl)
	if err != nil {
		return &GeneratedConstructor{
			FuncName:   funcName,
			StructName: structName,
		}, fmt.Errorf("failed to format constructor: %w", err)
	}

	return &GeneratedConstructor{
		FuncName:   funcName,
		StructName: structName,
		Code:       code,
	}, nil
}

// GenerateConstructorWithNamedDeps creates constructor code with named dependency parameters.
// Task 5.2: Supports custom parameter names for named dependencies.
func (g *constructorGenerator) GenerateConstructorWithNamedDeps(
	candidate detect.ConstructorCandidate, fields []detect.FieldInfo, info *registry.InjectorInfo,
	dependencyNames map[string]string,
) (*GeneratedConstructor, error) {
	// Task 5.1: Check WithoutConstructor option first
	if info != nil && info.OptionMetadata.WithoutConstructor {
		return nil, nil
	}

	structName := candidate.TypeSpec.Name.Name
	funcName := "New" + ToUpperCamelCase(structName)

	// Task 5.1: Determine return type based on options
	returnTypeExpr := g.determineReturnTypeExpr(structName, info)
	funcDecl := g.buildConstructorAST(funcName, structName, fields, returnTypeExpr, dependencyNames)

	code, err := renderDecl(funcDecl)
	if err != nil {
		return &GeneratedConstructor{
			FuncName:   funcName,
			StructName: structName,
		}, fmt.Errorf("failed to format constructor: %w", err)
	}

	return &GeneratedConstructor{
		FuncName:   funcName,
		StructName: structName,
		Code:       code,
	}, nil
}

// buildConstructorAST constructs the complete *ast.FuncDecl for a constructor.
// dependencyNames maps field names to custom parameter names (may be nil).
func (g *constructorGenerator) buildConstructorAST(
	funcName, structName string,
	fields []detect.FieldInfo,
	returnTypeExpr ast.Expr,
	dependencyNames map[string]string,
) *ast.FuncDecl {
	// Build doc comment
	doc := astCommentGroup(
		fmt.Sprintf("// %s is a constructor for %s.", funcName, structName),
		"//",
		"// Generated by braider. DO NOT EDIT.",
	)

	// Build parameter list
	var params []*ast.Field
	for _, field := range fields {
		paramName := g.resolveParamName(field.Name, dependencyNames)
		typ := field.TypeExpr
		if typ == nil {
			typ = astIdent("")
		}
		params = append(params, astField([]*ast.Ident{astIdent(paramName)}, typ))
	}

	// Build body: return &StructName{field: param, ...}
	var body *ast.BlockStmt
	if len(fields) > 0 {
		var elts []ast.Expr
		for _, field := range fields {
			paramName := g.resolveParamName(field.Name, dependencyNames)
			elts = append(elts, astKeyValue(astIdent(field.Name), astIdent(paramName)))
		}
		body = astBlockStmt(
			astReturnStmt(astAddr(astCompositeLit(astIdent(structName), elts...))),
		)
	} else {
		body = astBlockStmt(
			astReturnStmt(astAddr(astCompositeLit(astIdent(structName)))),
		)
	}

	paramList := astFieldList(params...)
	resultList := astFieldList(astField(nil, returnTypeExpr))

	return astFuncDecl(doc, funcName, paramList, resultList, body)
}

// resolveParamName returns the parameter name for a field.
// If dependencyNames has a custom name for the field, use it; otherwise derive from field name.
func (g *constructorGenerator) resolveParamName(fieldName string, dependencyNames map[string]string) string {
	if dependencyNames != nil {
		if customName, ok := dependencyNames[fieldName]; ok {
			return customName
		}
	}
	return DeriveParamName(fieldName)
}

// determineReturnTypeExpr determines constructor return type as an ast.Expr based on option metadata.
// Task 5.1: Returns interface type for Typed[I] option, pointer to struct otherwise.
func (g *constructorGenerator) determineReturnTypeExpr(structName string, info *registry.InjectorInfo) ast.Expr {
	if info == nil || info.OptionMetadata.TypedInterface == nil {
		// Default: return pointer to struct
		return astStar(astIdent(structName))
	}

	// Typed[I] option: return interface type
	typeStr := types.TypeString(
		info.OptionMetadata.TypedInterface, func(p *types.Package) string {
			// Use unqualified type name (same package context)
			return ""
		},
	)
	return parseExprString(typeStr)
}

// DeriveParamName converts a field name to a valid parameter name.
// Rules:
// 1. Convert to lowerCamelCase (handle all-caps like "DB" -> "db")
// 2. If result is a Go keyword, append underscore
// 3. If result conflicts with builtin, use field name with "Param" suffix
func DeriveParamName(fieldName string) string {
	if fieldName == "" {
		return "param"
	}

	// Convert to lowercase - handle all-caps names like "DB" -> "db"
	paramName := ToLowerCamelCase(fieldName)

	// Check for keyword conflicts
	if IsGoKeyword(paramName) {
		return paramName + "_"
	}

	// Check for builtin conflicts
	if IsGoBuiltin(paramName) {
		return paramName + "Param"
	}

	return paramName
}
