// Package annotation provides marker types and functions for braider's
// dependency injection code generation.
//
// This package defines annotations that instruct the braider analyzer
// to generate constructors, wiring code, and main function bootstrapping.
package annotation

import (
	"github.com/miyamo2/braider/internal/annotation"
	appopt "github.com/miyamo2/braider/pkg/annotation/app"
	"github.com/miyamo2/braider/pkg/annotation/inject"
	"github.com/miyamo2/braider/pkg/annotation/provide"
	variableopt "github.com/miyamo2/braider/pkg/annotation/variable"
)

// Injectable marks a struct as a dependency to be injected.
//
// The option type parameter controls registration and constructor behavior.
// Common options include:
//   - inject.Default: default registration, constructor returns *StructType
//   - inject.Typed[I]: register the dependency as interface type I
//   - inject.Named[N]: register the dependency with name N.Name()
//   - inject.WithoutConstructor: skip constructor generation (user must provide New<Type> manually)
//
// Example:
//
//	type Service struct {
//		annotation.Injectable[inject.Default]
//		repo Repository
//	}
//
//	type RepositoryImpl struct {
//		annotation.Injectable[inject.Typed[Repository]]
//	}
//
// Mixed options can be composed with embedded option interfaces:
//
//	type SpecialRepository struct {
//		annotation.Injectable[interface {
//			inject.Typed[Repository]
//			inject.Named[RepositoryName]
//		}]
//	}
type Injectable[T inject.Option] interface {
	annotation.Injectable
	option() T
}

type provider[T provide.Option] struct {
	annotation.Provider
}

func (p provider[T]) option() T {
	var zero T
	return zero
}

// Provide marks a function as a dependency provider.
//
// The option type parameter controls registration behavior.
//   - provide.Default: register the function's return type
//   - provide.Typed[I]: register the function as interface type I
//   - provide.Named[N]: register the function with name N.Name()
//
// Example:
//
//	var _ = annotation.Provide[provide.Default](NewRepository)
//	var _ = annotation.Provide[provide.Typed[Repository]](NewRepository)
//	var _ = annotation.Provide[provide.Named[PrimaryRepoName]](NewRepository)
func Provide[T provide.Option](providerFunc any) provider[T] {
	_ = providerFunc
	return provider[T]{}
}

type app[T appopt.Option] struct {
	annotation.App
	opt T
}

func (a app[T]) option() T {
	var zero T
	return zero
}

// App marks the entry point for bootstrap code generation.
//
// When App is declared, braider generates an IIFE that initializes
// all registered dependencies in topological order.
//
// Example:
//
//	package main
//
//	import (
//		"time"
//
//		"github.com/miyamo2/braider/pkg/annotation"
//		"github.com/miyamo2/braider/pkg/annotation/app"
//		"github.com/miyamo2/braider/pkg/annotation/inject"
//		"github.com/miyamo2/braider/pkg/annotation/provide"
//	)
//
//	type Clock interface {
//		Now() time.Time
//	}
//
//	type realClock struct{}
//
//	func (realClock) Now() time.Time { return time.Now() }
//
//	var _ = annotation.Provide[provide.Typed[Clock]](NewClock)
//
//	func NewClock() *realClock { return &realClock{} }
//
//	type Service struct {
//		annotation.Injectable[inject.Default]
//		Clock Clock
//	}
//
//	var _ = annotation.App[app.Default](main)
//
//	func main() {}
//
// Example generated main function:
//
//	package main
//
//	import (
//		"time"
//
//		"github.com/miyamo2/braider/pkg/annotation"
//		"github.com/miyamo2/braider/pkg/annotation/app"
//		"github.com/miyamo2/braider/pkg/annotation/inject"
//		"github.com/miyamo2/braider/pkg/annotation/provide"
//	)
//
//	type Clock interface {
//		Now() time.Time
//	}
//
//	type realClock struct{}
//
//	func (realClock) Now() time.Time { return time.Now() }
//
//	var _ = annotation.Provide[provide.Typed[Clock]](NewClock)
//
//	func NewClock() *realClock { return &realClock{} }
//
//	type Service struct {
//		annotation.Injectable[inject.Default]
//		Clock Clock
//	}
//
//	// NewService is a constructor for Service.
//	//
//	// Generated by braider. DO NOT EDIT.
//	func NewService(clock Clock) *Service {
//		return &Service{
//			Clock: clock,
//		}
//	}
//
//	var _ = annotation.App[app.Default](main)
//
//	func main() {
//		_ = dependency
//	}
//
//	// braider:hash:<hash>
//	var dependency = func() struct {
//		clock   Clock
//		service *Service
//	} {
//		clock := NewClock()
//		service := NewService(clock)
//		return struct {
//			clock   Clock
//			service *Service
//		}{
//			clock:   clock,
//			service: service,
//		}
//	}()
func App[T appopt.Option](mainFunc func()) annotation.App {
	_ = mainFunc
	return app[T]{}
}

type _variable[T variableopt.Option] struct {
	annotation.Variable
}

func (v _variable[T]) option() T {
	var zero T
	return zero
}

// Variable marks a variable as a dependency to be provided.
//
// The option type parameter controls registration behavior.
//   - variable.Default: register the variable under its declared type
//   - variable.Typed[I]: register the variable as type I
//   - variable.Named[N]: register the variable with name N.Name()
//
// Example:
//
//	var _ = annotation.Variable[variable.Default](os.Stdout)
func Variable[T variableopt.Option](variable any) _variable[T] {
	_ = variable
	return _variable[T]{}
}
